package mapper;

import models.HhtMember;

public interface HhtMemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hht_member
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hht_member
     *
     * @mbg.generated
     */
    int insert(HhtMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hht_member
     *
     * @mbg.generated
     */
    int insertSelective(HhtMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hht_member
     *
     * @mbg.generated
     */
    HhtMember selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hht_member
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HhtMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hht_member
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HhtMember record);
}