package mapper;

import com.hht.interceptor.Page;
import models.ProEliteTrainRepository;

import java.util.List;
import java.util.Map;

public interface ProEliteTrainRepositoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_elite_train_repository
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_elite_train_repository
     *
     * @mbg.generated
     */
    int insert(ProEliteTrainRepository record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_elite_train_repository
     *
     * @mbg.generated
     */
    int insertSelective(ProEliteTrainRepository record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_elite_train_repository
     *
     * @mbg.generated
     */
    ProEliteTrainRepository selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_elite_train_repository
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ProEliteTrainRepository record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_elite_train_repository
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProEliteTrainRepository record);

    List<Map<String,Object>> getRepositoryByListPage(Page page);
    List<Map<String,Object>> getRepository();
}