package mapper;

import com.hht.interceptor.Page;
import models.ProEliteGroom;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface ProEliteGroomMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_elite_groom
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_elite_groom
     *
     * @mbg.generated
     */
    int insert(ProEliteGroom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_elite_groom
     *
     * @mbg.generated
     */
    int insertSelective(ProEliteGroom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_elite_groom
     *
     * @mbg.generated
     */
    ProEliteGroom selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_elite_groom
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ProEliteGroom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_elite_groom
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProEliteGroom record);

  //  List<EliteGroomVo>  getEliteGroomsByPage(Page page);
    List<Map<String,Object>> getEliteGroomsByListPage(Page page);

    int updateEliteClassGroomByEmployeeId(ProEliteGroom groom);
    int updateByEmployeeCodeByList(List<ProEliteGroom> groom);

    List<Map<String,Object>> getShopSelfGroomToLobby(Map<String,Object> map);

    List<Map<String,Object>> getShopSelfGroomToLaksaClass(Map<String, Object> map);

    List<Map<String,Object>> getGroomEmployeesByListPage(Page page);

    int selectToClassCountByEmPloyeeId(ProEliteGroom eliteGroom);

    List<ProEliteGroom> getGroomEmployees(Map<String, Object> mapParams);

    void updateGroomEmployeeByCreateTime(String employeeId);

    List<Map<String,Object>> getPropertyInformationListPage(Page page);

    void updateEliteClassGroomByEmployeeCode(List<Map<String, Object>> mapList);
}