package mapper;

import com.hht.interceptor.Page;
import models.ProEliteNotice;

import java.util.List;
import java.util.Map;

public interface ProEliteNoticeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_elite_notice
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_elite_notice
     *
     * @mbg.generated
     */
    int insert(ProEliteNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_elite_notice
     *
     * @mbg.generated
     */
    int insertSelective(ProEliteNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_elite_notice
     *
     * @mbg.generated
     */
    ProEliteNotice selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_elite_notice
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ProEliteNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_elite_notice
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProEliteNotice record);


    List<ProEliteNotice> getEliteNoticesByListPage(Page page);

    int updateEliteNoticeByList(List<ProEliteNotice> list);


    ProEliteNotice queryNoticeByNoticeCode(Map<String,Object> params);

    int insertBatchProEliteNotice(ProEliteNotice record);
}