package mapper;

import com.hht.interceptor.Page;
import models.ProEliteClass;

import java.util.List;
import java.util.Map;

public interface ProEliteClassMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_elite_class
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_elite_class
     *
     * @mbg.generated
     */
    int insert(ProEliteClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_elite_class
     *
     * @mbg.generated
     */
    int insertSelective(ProEliteClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_elite_class
     *
     * @mbg.generated
     */
    ProEliteClass selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_elite_class
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ProEliteClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_elite_class
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProEliteClass record);

    List<ProEliteClass> getProEliteClasssByListPage(Page page);

    ProEliteClass selectByMap(Map<String, Object> mapParams);

    ProEliteClass getTermByEmployeeCode(Map<String, Object> mapParams);
    ProEliteClass getClassByEmployeeCode(Map<String, Object> mapParams);

    /**
     * 分页查询班级
     * @param page
     * @return
     */
    List<ProEliteClass> getClassByListPage(Page page);
    void setProEliteClass(List<ProEliteClass> list);

    List<ProEliteClass> getClassByClassType(ProEliteClass proEliteClass);
}