package mapper;

import models.ProEmployeePosition;

public interface ProEmployeePositionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_employee_position
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_employee_position
     *
     * @mbg.generated
     */
    int insert(ProEmployeePosition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_employee_position
     *
     * @mbg.generated
     */
    int insertSelective(ProEmployeePosition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_employee_position
     *
     * @mbg.generated
     */
    ProEmployeePosition selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_employee_position
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ProEmployeePosition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_employee_position
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProEmployeePosition record);

    int selectCountByShopId(ProEmployeePosition position);
}