package mapper;

import models.ProEliteTestRecord;

import java.util.List;
import java.util.Map;

public interface ProEliteTestRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_elite_test_record
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_elite_test_record
     *
     * @mbg.generated
     */
    int insert(ProEliteTestRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_elite_test_record
     *
     * @mbg.generated
     */
    int insertSelective(ProEliteTestRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_elite_test_record
     *
     * @mbg.generated
     */
    ProEliteTestRecord selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_elite_test_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ProEliteTestRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_elite_test_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProEliteTestRecord record);

    void batchInsertRecord(List<ProEliteTestRecord> list);

    List<ProEliteTestRecord> queryListByTestOnceId(List<String> list);

    void batchUpdateById(List<ProEliteTestRecord> list);

    void updateByTestId(ProEliteTestRecord record);

    List<ProEliteTestRecord> getTestNotRecord();
    List<ProEliteTestRecord> getTestByEmployee(Map<String,Object> params);

    ProEliteTestRecord queryRecordByTestOnceId(String testOnceId);

    void batchUpdateForTestEnd(List<ProEliteTestRecord> list);

    int updateByEmployeeCode(String employeeCode);

    /**
     * 查询出在金鹰池未测评人员
     * @param list
     * @return
     */
    List<ProEliteTestRecord> queryList(List<Map<String, Object>> list);

    List<ProEliteTestRecord> queryForTestEnd();
}