package mapper;

import models.ProEliteNoticeRecord;

import java.util.List;
import java.util.Map;

public interface ProEliteNoticeRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_elite_notice_record
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_elite_notice_record
     *
     * @mbg.generated
     */
    int insert(ProEliteNoticeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_elite_notice_record
     *
     * @mbg.generated
     */
    int insertSelective(ProEliteNoticeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_elite_notice_record
     *
     * @mbg.generated
     */
    ProEliteNoticeRecord selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_elite_notice_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ProEliteNoticeRecord record);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_elite_notice_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProEliteNoticeRecord record);

    List<ProEliteNoticeRecord> getLaksaSelfNoticeRecords(Map<String, Object> mapParams);
    List<ProEliteNoticeRecord> getNoticeByEmployeeCode(Map<String, Object> mapParams);

    int getUnreadNoticeCount(Map<String, Object> mapParams);

    int updateByEmployeeCode(String employeeCode);

    void batchInsertNoticeRecord(List<ProEliteNoticeRecord> list);
}