package mapper;

import models.ProFileRelation;

import java.util.List;
import java.util.Map;

public interface ProFileRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_file_relation
     *
     * @mbggenerated Mon Apr 10 15:29:07 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_file_relation
     *
     * @mbggenerated Mon Apr 10 15:29:07 CST 2017
     */
    int insert(ProFileRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_file_relation
     *
     * @mbggenerated Mon Apr 10 15:29:07 CST 2017
     */
    int insertSelective(ProFileRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_file_relation
     *
     * @mbggenerated Mon Apr 10 15:29:07 CST 2017
     */
    ProFileRelation selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_file_relation
     *
     * @mbggenerated Mon Apr 10 15:29:07 CST 2017
     */
    int updateByPrimaryKeySelective(ProFileRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_file_relation
     *
     * @mbggenerated Mon Apr 10 15:29:07 CST 2017
     */
    int updateByPrimaryKey(ProFileRelation record);

    int addBatch(List<ProFileRelation> list);

    int updateBatch(List<ProFileRelation> list);

    int deleteBatch(Map param);

    int deleteBatchById(Map param);

    List<ProFileRelation> selectAll(ProFileRelation proFileRelation);
}