package mapper;

import models.ProPosition;

import java.util.List;

public interface ProPositionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_position
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_position
     *
     * @mbg.generated
     */
    int insert(ProPosition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_position
     *
     * @mbg.generated
     */
    int insertSelective(ProPosition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_position
     *
     * @mbg.generated
     */
    ProPosition selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_position
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ProPosition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_position
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProPosition record);

    List<ProPosition> getPositions();
}