package mapper;

import models.ProShopEliteEmployee;

public interface ProShopEliteEmployeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_shop_elite_employee
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_shop_elite_employee
     *
     * @mbg.generated
     */
    int insert(ProShopEliteEmployee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_shop_elite_employee
     *
     * @mbg.generated
     */
    int insertSelective(ProShopEliteEmployee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_shop_elite_employee
     *
     * @mbg.generated
     */
    ProShopEliteEmployee selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_shop_elite_employee
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ProShopEliteEmployee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pro_shop_elite_employee
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProShopEliteEmployee record);
}