package models;

public class HhtMember {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hht_member.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hht_member.member_code
     *
     * @mbg.generated
     */
    private String memberCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hht_member.member_name
     *
     * @mbg.generated
     */
    private String memberName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hht_member.nationality_id
     *
     * @mbg.generated
     */
    private String nationalityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hht_member.paper_type_id
     *
     * @mbg.generated
     */
    private String paperTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hht_member.paper_no
     *
     * @mbg.generated
     */
    private String paperNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hht_member.verify_pic1
     *
     * @mbg.generated
     */
    private String verifyPic1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hht_member.verify_pic2
     *
     * @mbg.generated
     */
    private String verifyPic2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hht_member.verify_pic3
     *
     * @mbg.generated
     */
    private String verifyPic3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hht_member.login_acc
     *
     * @mbg.generated
     */
    private String loginAcc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hht_member.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hht_member.system_list
     *
     * @mbg.generated
     */
    private String systemList;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hht_member.gender
     *
     * @mbg.generated
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hht_member.mobile_no
     *
     * @mbg.generated
     */
    private String mobileNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hht_member.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hht_member.first_login_time
     *
     * @mbg.generated
     */
    private Long firstLoginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hht_member.last_login_time
     *
     * @mbg.generated
     */
    private Long lastLoginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hht_member.login_number
     *
     * @mbg.generated
     */
    private Integer loginNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hht_member.source_type
     *
     * @mbg.generated
     */
    private String sourceType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hht_member.source_id
     *
     * @mbg.generated
     */
    private String sourceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hht_member.create_time
     *
     * @mbg.generated
     */
    private Long createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hht_member.enable
     *
     * @mbg.generated
     */
    private String enable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hht_member.disable_time
     *
     * @mbg.generated
     */
    private Long disableTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hht_member.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hht_member.dr
     *
     * @mbg.generated
     */
    private String dr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hht_member.ts
     *
     * @mbg.generated
     */
    private Long ts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hht_member.graph_password
     *
     * @mbg.generated
     */
    private String graphPassword;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hht_member.id
     *
     * @return the value of hht_member.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hht_member.id
     *
     * @param id the value for hht_member.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hht_member.member_code
     *
     * @return the value of hht_member.member_code
     *
     * @mbg.generated
     */
    public String getMemberCode() {
        return memberCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hht_member.member_code
     *
     * @param memberCode the value for hht_member.member_code
     *
     * @mbg.generated
     */
    public void setMemberCode(String memberCode) {
        this.memberCode = memberCode == null ? null : memberCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hht_member.member_name
     *
     * @return the value of hht_member.member_name
     *
     * @mbg.generated
     */
    public String getMemberName() {
        return memberName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hht_member.member_name
     *
     * @param memberName the value for hht_member.member_name
     *
     * @mbg.generated
     */
    public void setMemberName(String memberName) {
        this.memberName = memberName == null ? null : memberName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hht_member.nationality_id
     *
     * @return the value of hht_member.nationality_id
     *
     * @mbg.generated
     */
    public String getNationalityId() {
        return nationalityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hht_member.nationality_id
     *
     * @param nationalityId the value for hht_member.nationality_id
     *
     * @mbg.generated
     */
    public void setNationalityId(String nationalityId) {
        this.nationalityId = nationalityId == null ? null : nationalityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hht_member.paper_type_id
     *
     * @return the value of hht_member.paper_type_id
     *
     * @mbg.generated
     */
    public String getPaperTypeId() {
        return paperTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hht_member.paper_type_id
     *
     * @param paperTypeId the value for hht_member.paper_type_id
     *
     * @mbg.generated
     */
    public void setPaperTypeId(String paperTypeId) {
        this.paperTypeId = paperTypeId == null ? null : paperTypeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hht_member.paper_no
     *
     * @return the value of hht_member.paper_no
     *
     * @mbg.generated
     */
    public String getPaperNo() {
        return paperNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hht_member.paper_no
     *
     * @param paperNo the value for hht_member.paper_no
     *
     * @mbg.generated
     */
    public void setPaperNo(String paperNo) {
        this.paperNo = paperNo == null ? null : paperNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hht_member.verify_pic1
     *
     * @return the value of hht_member.verify_pic1
     *
     * @mbg.generated
     */
    public String getVerifyPic1() {
        return verifyPic1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hht_member.verify_pic1
     *
     * @param verifyPic1 the value for hht_member.verify_pic1
     *
     * @mbg.generated
     */
    public void setVerifyPic1(String verifyPic1) {
        this.verifyPic1 = verifyPic1 == null ? null : verifyPic1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hht_member.verify_pic2
     *
     * @return the value of hht_member.verify_pic2
     *
     * @mbg.generated
     */
    public String getVerifyPic2() {
        return verifyPic2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hht_member.verify_pic2
     *
     * @param verifyPic2 the value for hht_member.verify_pic2
     *
     * @mbg.generated
     */
    public void setVerifyPic2(String verifyPic2) {
        this.verifyPic2 = verifyPic2 == null ? null : verifyPic2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hht_member.verify_pic3
     *
     * @return the value of hht_member.verify_pic3
     *
     * @mbg.generated
     */
    public String getVerifyPic3() {
        return verifyPic3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hht_member.verify_pic3
     *
     * @param verifyPic3 the value for hht_member.verify_pic3
     *
     * @mbg.generated
     */
    public void setVerifyPic3(String verifyPic3) {
        this.verifyPic3 = verifyPic3 == null ? null : verifyPic3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hht_member.login_acc
     *
     * @return the value of hht_member.login_acc
     *
     * @mbg.generated
     */
    public String getLoginAcc() {
        return loginAcc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hht_member.login_acc
     *
     * @param loginAcc the value for hht_member.login_acc
     *
     * @mbg.generated
     */
    public void setLoginAcc(String loginAcc) {
        this.loginAcc = loginAcc == null ? null : loginAcc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hht_member.password
     *
     * @return the value of hht_member.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hht_member.password
     *
     * @param password the value for hht_member.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hht_member.system_list
     *
     * @return the value of hht_member.system_list
     *
     * @mbg.generated
     */
    public String getSystemList() {
        return systemList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hht_member.system_list
     *
     * @param systemList the value for hht_member.system_list
     *
     * @mbg.generated
     */
    public void setSystemList(String systemList) {
        this.systemList = systemList == null ? null : systemList.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hht_member.gender
     *
     * @return the value of hht_member.gender
     *
     * @mbg.generated
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hht_member.gender
     *
     * @param gender the value for hht_member.gender
     *
     * @mbg.generated
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hht_member.mobile_no
     *
     * @return the value of hht_member.mobile_no
     *
     * @mbg.generated
     */
    public String getMobileNo() {
        return mobileNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hht_member.mobile_no
     *
     * @param mobileNo the value for hht_member.mobile_no
     *
     * @mbg.generated
     */
    public void setMobileNo(String mobileNo) {
        this.mobileNo = mobileNo == null ? null : mobileNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hht_member.email
     *
     * @return the value of hht_member.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hht_member.email
     *
     * @param email the value for hht_member.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hht_member.first_login_time
     *
     * @return the value of hht_member.first_login_time
     *
     * @mbg.generated
     */
    public Long getFirstLoginTime() {
        return firstLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hht_member.first_login_time
     *
     * @param firstLoginTime the value for hht_member.first_login_time
     *
     * @mbg.generated
     */
    public void setFirstLoginTime(Long firstLoginTime) {
        this.firstLoginTime = firstLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hht_member.last_login_time
     *
     * @return the value of hht_member.last_login_time
     *
     * @mbg.generated
     */
    public Long getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hht_member.last_login_time
     *
     * @param lastLoginTime the value for hht_member.last_login_time
     *
     * @mbg.generated
     */
    public void setLastLoginTime(Long lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hht_member.login_number
     *
     * @return the value of hht_member.login_number
     *
     * @mbg.generated
     */
    public Integer getLoginNumber() {
        return loginNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hht_member.login_number
     *
     * @param loginNumber the value for hht_member.login_number
     *
     * @mbg.generated
     */
    public void setLoginNumber(Integer loginNumber) {
        this.loginNumber = loginNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hht_member.source_type
     *
     * @return the value of hht_member.source_type
     *
     * @mbg.generated
     */
    public String getSourceType() {
        return sourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hht_member.source_type
     *
     * @param sourceType the value for hht_member.source_type
     *
     * @mbg.generated
     */
    public void setSourceType(String sourceType) {
        this.sourceType = sourceType == null ? null : sourceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hht_member.source_id
     *
     * @return the value of hht_member.source_id
     *
     * @mbg.generated
     */
    public String getSourceId() {
        return sourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hht_member.source_id
     *
     * @param sourceId the value for hht_member.source_id
     *
     * @mbg.generated
     */
    public void setSourceId(String sourceId) {
        this.sourceId = sourceId == null ? null : sourceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hht_member.create_time
     *
     * @return the value of hht_member.create_time
     *
     * @mbg.generated
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hht_member.create_time
     *
     * @param createTime the value for hht_member.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hht_member.enable
     *
     * @return the value of hht_member.enable
     *
     * @mbg.generated
     */
    public String getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hht_member.enable
     *
     * @param enable the value for hht_member.enable
     *
     * @mbg.generated
     */
    public void setEnable(String enable) {
        this.enable = enable == null ? null : enable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hht_member.disable_time
     *
     * @return the value of hht_member.disable_time
     *
     * @mbg.generated
     */
    public Long getDisableTime() {
        return disableTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hht_member.disable_time
     *
     * @param disableTime the value for hht_member.disable_time
     *
     * @mbg.generated
     */
    public void setDisableTime(Long disableTime) {
        this.disableTime = disableTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hht_member.remark
     *
     * @return the value of hht_member.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hht_member.remark
     *
     * @param remark the value for hht_member.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hht_member.dr
     *
     * @return the value of hht_member.dr
     *
     * @mbg.generated
     */
    public String getDr() {
        return dr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hht_member.dr
     *
     * @param dr the value for hht_member.dr
     *
     * @mbg.generated
     */
    public void setDr(String dr) {
        this.dr = dr == null ? null : dr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hht_member.ts
     *
     * @return the value of hht_member.ts
     *
     * @mbg.generated
     */
    public Long getTs() {
        return ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hht_member.ts
     *
     * @param ts the value for hht_member.ts
     *
     * @mbg.generated
     */
    public void setTs(Long ts) {
        this.ts = ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hht_member.graph_password
     *
     * @return the value of hht_member.graph_password
     *
     * @mbg.generated
     */
    public String getGraphPassword() {
        return graphPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hht_member.graph_password
     *
     * @param graphPassword the value for hht_member.graph_password
     *
     * @mbg.generated
     */
    public void setGraphPassword(String graphPassword) {
        this.graphPassword = graphPassword == null ? null : graphPassword.trim();
    }
}