package models;

public class ProEliteTrainPool {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_train_pool.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_train_pool.elite_per
     *
     * @mbg.generated
     */
    private Integer elitePer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_train_pool.up_per
     *
     * @mbg.generated
     */
    private Integer upPer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_train_pool.warn_per
     *
     * @mbg.generated
     */
    private Integer warnPer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_train_pool.reserve_sign_time
     *
     * @mbg.generated
     */
    private Integer reserveSignTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_train_pool.lobby_sign_time
     *
     * @mbg.generated
     */
    private Integer lobbySignTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_train_pool.warn_time
     *
     * @mbg.generated
     */
    private Integer warnTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_train_pool.creator_id
     *
     * @mbg.generated
     */
    private String creatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_train_pool.create_time
     *
     * @mbg.generated
     */
    private Long createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_train_pool.modifier_id
     *
     * @mbg.generated
     */
    private String modifierId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_train_pool.modify_time
     *
     * @mbg.generated
     */
    private Long modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_train_pool.ts
     *
     * @mbg.generated
     */
    private Long ts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_train_pool.dr
     *
     * @mbg.generated
     */
    private String dr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_train_pool.lobby_msg
     *
     * @mbg.generated
     */
    private String lobbyMsg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_train_pool.reserve_msg
     *
     * @mbg.generated
     */
    private String reserveMsg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_train_pool.id
     *
     * @return the value of pro_elite_train_pool.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_train_pool.id
     *
     * @param id the value for pro_elite_train_pool.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_train_pool.elite_per
     *
     * @return the value of pro_elite_train_pool.elite_per
     *
     * @mbg.generated
     */
    public Integer getElitePer() {
        return elitePer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_train_pool.elite_per
     *
     * @param elitePer the value for pro_elite_train_pool.elite_per
     *
     * @mbg.generated
     */
    public void setElitePer(Integer elitePer) {
        this.elitePer = elitePer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_train_pool.up_per
     *
     * @return the value of pro_elite_train_pool.up_per
     *
     * @mbg.generated
     */
    public Integer getUpPer() {
        return upPer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_train_pool.up_per
     *
     * @param upPer the value for pro_elite_train_pool.up_per
     *
     * @mbg.generated
     */
    public void setUpPer(Integer upPer) {
        this.upPer = upPer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_train_pool.warn_per
     *
     * @return the value of pro_elite_train_pool.warn_per
     *
     * @mbg.generated
     */
    public Integer getWarnPer() {
        return warnPer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_train_pool.warn_per
     *
     * @param warnPer the value for pro_elite_train_pool.warn_per
     *
     * @mbg.generated
     */
    public void setWarnPer(Integer warnPer) {
        this.warnPer = warnPer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_train_pool.reserve_sign_time
     *
     * @return the value of pro_elite_train_pool.reserve_sign_time
     *
     * @mbg.generated
     */
    public Integer getReserveSignTime() {
        return reserveSignTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_train_pool.reserve_sign_time
     *
     * @param reserveSignTime the value for pro_elite_train_pool.reserve_sign_time
     *
     * @mbg.generated
     */
    public void setReserveSignTime(Integer reserveSignTime) {
        this.reserveSignTime = reserveSignTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_train_pool.lobby_sign_time
     *
     * @return the value of pro_elite_train_pool.lobby_sign_time
     *
     * @mbg.generated
     */
    public Integer getLobbySignTime() {
        return lobbySignTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_train_pool.lobby_sign_time
     *
     * @param lobbySignTime the value for pro_elite_train_pool.lobby_sign_time
     *
     * @mbg.generated
     */
    public void setLobbySignTime(Integer lobbySignTime) {
        this.lobbySignTime = lobbySignTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_train_pool.warn_time
     *
     * @return the value of pro_elite_train_pool.warn_time
     *
     * @mbg.generated
     */
    public Integer getWarnTime() {
        return warnTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_train_pool.warn_time
     *
     * @param warnTime the value for pro_elite_train_pool.warn_time
     *
     * @mbg.generated
     */
    public void setWarnTime(Integer warnTime) {
        this.warnTime = warnTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_train_pool.creator_id
     *
     * @return the value of pro_elite_train_pool.creator_id
     *
     * @mbg.generated
     */
    public String getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_train_pool.creator_id
     *
     * @param creatorId the value for pro_elite_train_pool.creator_id
     *
     * @mbg.generated
     */
    public void setCreatorId(String creatorId) {
        this.creatorId = creatorId == null ? null : creatorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_train_pool.create_time
     *
     * @return the value of pro_elite_train_pool.create_time
     *
     * @mbg.generated
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_train_pool.create_time
     *
     * @param createTime the value for pro_elite_train_pool.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_train_pool.modifier_id
     *
     * @return the value of pro_elite_train_pool.modifier_id
     *
     * @mbg.generated
     */
    public String getModifierId() {
        return modifierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_train_pool.modifier_id
     *
     * @param modifierId the value for pro_elite_train_pool.modifier_id
     *
     * @mbg.generated
     */
    public void setModifierId(String modifierId) {
        this.modifierId = modifierId == null ? null : modifierId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_train_pool.modify_time
     *
     * @return the value of pro_elite_train_pool.modify_time
     *
     * @mbg.generated
     */
    public Long getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_train_pool.modify_time
     *
     * @param modifyTime the value for pro_elite_train_pool.modify_time
     *
     * @mbg.generated
     */
    public void setModifyTime(Long modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_train_pool.ts
     *
     * @return the value of pro_elite_train_pool.ts
     *
     * @mbg.generated
     */
    public Long getTs() {
        return ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_train_pool.ts
     *
     * @param ts the value for pro_elite_train_pool.ts
     *
     * @mbg.generated
     */
    public void setTs(Long ts) {
        this.ts = ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_train_pool.dr
     *
     * @return the value of pro_elite_train_pool.dr
     *
     * @mbg.generated
     */
    public String getDr() {
        return dr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_train_pool.dr
     *
     * @param dr the value for pro_elite_train_pool.dr
     *
     * @mbg.generated
     */
    public void setDr(String dr) {
        this.dr = dr == null ? null : dr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_train_pool.lobby_msg
     *
     * @return the value of pro_elite_train_pool.lobby_msg
     *
     * @mbg.generated
     */
    public String getLobbyMsg() {
        return lobbyMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_train_pool.lobby_msg
     *
     * @param lobbyMsg the value for pro_elite_train_pool.lobby_msg
     *
     * @mbg.generated
     */
    public void setLobbyMsg(String lobbyMsg) {
        this.lobbyMsg = lobbyMsg == null ? null : lobbyMsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_train_pool.reserve_msg
     *
     * @return the value of pro_elite_train_pool.reserve_msg
     *
     * @mbg.generated
     */
    public String getReserveMsg() {
        return reserveMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_train_pool.reserve_msg
     *
     * @param reserveMsg the value for pro_elite_train_pool.reserve_msg
     *
     * @mbg.generated
     */
    public void setReserveMsg(String reserveMsg) {
        this.reserveMsg = reserveMsg == null ? null : reserveMsg.trim();
    }
}