package models;

public class ProEliteTrainRepository {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_train_repository.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_train_repository.property_id
     *
     * @mbg.generated
     */
    private String propertyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_train_repository.file_name
     *
     * @mbg.generated
     */
    private String fileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_train_repository.file_cover_url
     *
     * @mbg.generated
     */
    private String fileCoverUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_train_repository.file_url
     *
     * @mbg.generated
     */
    private String fileUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_train_repository.is_down
     *
     * @mbg.generated
     */
    private String isDown;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_train_repository.operator_id
     *
     * @mbg.generated
     */
    private String operatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_train_repository.operate_time
     *
     * @mbg.generated
     */
    private Long operateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_train_repository.creator_id
     *
     * @mbg.generated
     */
    private String creatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_train_repository.create_time
     *
     * @mbg.generated
     */
    private Long createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_train_repository.modifier_id
     *
     * @mbg.generated
     */
    private String modifierId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_train_repository.dr
     *
     * @mbg.generated
     */
    private String dr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_train_repository.modify_time
     *
     * @mbg.generated
     */
    private Long modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_train_repository.ts
     *
     * @mbg.generated
     */
    private Long ts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_train_repository.file_app_url
     *
     * @mbg.generated
     */
    private String fileAppUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_train_repository.file_app_cover
     *
     * @mbg.generated
     */
    private String fileAppCover;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_train_repository.id
     *
     * @return the value of pro_elite_train_repository.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_train_repository.id
     *
     * @param id the value for pro_elite_train_repository.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_train_repository.property_id
     *
     * @return the value of pro_elite_train_repository.property_id
     *
     * @mbg.generated
     */
    public String getPropertyId() {
        return propertyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_train_repository.property_id
     *
     * @param propertyId the value for pro_elite_train_repository.property_id
     *
     * @mbg.generated
     */
    public void setPropertyId(String propertyId) {
        this.propertyId = propertyId == null ? null : propertyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_train_repository.file_name
     *
     * @return the value of pro_elite_train_repository.file_name
     *
     * @mbg.generated
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_train_repository.file_name
     *
     * @param fileName the value for pro_elite_train_repository.file_name
     *
     * @mbg.generated
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_train_repository.file_cover_url
     *
     * @return the value of pro_elite_train_repository.file_cover_url
     *
     * @mbg.generated
     */
    public String getFileCoverUrl() {
        return fileCoverUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_train_repository.file_cover_url
     *
     * @param fileCoverUrl the value for pro_elite_train_repository.file_cover_url
     *
     * @mbg.generated
     */
    public void setFileCoverUrl(String fileCoverUrl) {
        this.fileCoverUrl = fileCoverUrl == null ? null : fileCoverUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_train_repository.file_url
     *
     * @return the value of pro_elite_train_repository.file_url
     *
     * @mbg.generated
     */
    public String getFileUrl() {
        return fileUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_train_repository.file_url
     *
     * @param fileUrl the value for pro_elite_train_repository.file_url
     *
     * @mbg.generated
     */
    public void setFileUrl(String fileUrl) {
        this.fileUrl = fileUrl == null ? null : fileUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_train_repository.is_down
     *
     * @return the value of pro_elite_train_repository.is_down
     *
     * @mbg.generated
     */
    public String getIsDown() {
        return isDown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_train_repository.is_down
     *
     * @param isDown the value for pro_elite_train_repository.is_down
     *
     * @mbg.generated
     */
    public void setIsDown(String isDown) {
        this.isDown = isDown == null ? null : isDown.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_train_repository.operator_id
     *
     * @return the value of pro_elite_train_repository.operator_id
     *
     * @mbg.generated
     */
    public String getOperatorId() {
        return operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_train_repository.operator_id
     *
     * @param operatorId the value for pro_elite_train_repository.operator_id
     *
     * @mbg.generated
     */
    public void setOperatorId(String operatorId) {
        this.operatorId = operatorId == null ? null : operatorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_train_repository.operate_time
     *
     * @return the value of pro_elite_train_repository.operate_time
     *
     * @mbg.generated
     */
    public Long getOperateTime() {
        return operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_train_repository.operate_time
     *
     * @param operateTime the value for pro_elite_train_repository.operate_time
     *
     * @mbg.generated
     */
    public void setOperateTime(Long operateTime) {
        this.operateTime = operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_train_repository.creator_id
     *
     * @return the value of pro_elite_train_repository.creator_id
     *
     * @mbg.generated
     */
    public String getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_train_repository.creator_id
     *
     * @param creatorId the value for pro_elite_train_repository.creator_id
     *
     * @mbg.generated
     */
    public void setCreatorId(String creatorId) {
        this.creatorId = creatorId == null ? null : creatorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_train_repository.create_time
     *
     * @return the value of pro_elite_train_repository.create_time
     *
     * @mbg.generated
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_train_repository.create_time
     *
     * @param createTime the value for pro_elite_train_repository.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_train_repository.modifier_id
     *
     * @return the value of pro_elite_train_repository.modifier_id
     *
     * @mbg.generated
     */
    public String getModifierId() {
        return modifierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_train_repository.modifier_id
     *
     * @param modifierId the value for pro_elite_train_repository.modifier_id
     *
     * @mbg.generated
     */
    public void setModifierId(String modifierId) {
        this.modifierId = modifierId == null ? null : modifierId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_train_repository.dr
     *
     * @return the value of pro_elite_train_repository.dr
     *
     * @mbg.generated
     */
    public String getDr() {
        return dr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_train_repository.dr
     *
     * @param dr the value for pro_elite_train_repository.dr
     *
     * @mbg.generated
     */
    public void setDr(String dr) {
        this.dr = dr == null ? null : dr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_train_repository.modify_time
     *
     * @return the value of pro_elite_train_repository.modify_time
     *
     * @mbg.generated
     */
    public Long getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_train_repository.modify_time
     *
     * @param modifyTime the value for pro_elite_train_repository.modify_time
     *
     * @mbg.generated
     */
    public void setModifyTime(Long modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_train_repository.ts
     *
     * @return the value of pro_elite_train_repository.ts
     *
     * @mbg.generated
     */
    public Long getTs() {
        return ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_train_repository.ts
     *
     * @param ts the value for pro_elite_train_repository.ts
     *
     * @mbg.generated
     */
    public void setTs(Long ts) {
        this.ts = ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_train_repository.file_app_url
     *
     * @return the value of pro_elite_train_repository.file_app_url
     *
     * @mbg.generated
     */
    public String getFileAppUrl() {
        return fileAppUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_train_repository.file_app_url
     *
     * @param fileAppUrl the value for pro_elite_train_repository.file_app_url
     *
     * @mbg.generated
     */
    public void setFileAppUrl(String fileAppUrl) {
        this.fileAppUrl = fileAppUrl == null ? null : fileAppUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_train_repository.file_app_cover
     *
     * @return the value of pro_elite_train_repository.file_app_cover
     *
     * @mbg.generated
     */
    public String getFileAppCover() {
        return fileAppCover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_train_repository.file_app_cover
     *
     * @param fileAppCover the value for pro_elite_train_repository.file_app_cover
     *
     * @mbg.generated
     */
    public void setFileAppCover(String fileAppCover) {
        this.fileAppCover = fileAppCover == null ? null : fileAppCover.trim();
    }
}