package models;

public class ProEliteExaminationOnline {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_examination_online.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_examination_online.employee_id
     *
     * @mbg.generated
     */
    private String employeeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_examination_online.employee_code
     *
     * @mbg.generated
     */
    private String employeeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_examination_online.relult_score
     *
     * @mbg.generated
     */
    private Integer relultScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_examination_online.pass_score
     *
     * @mbg.generated
     */
    private Integer passScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_examination_online.is_pass
     *
     * @mbg.generated
     */
    private String isPass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_examination_online.creator_id
     *
     * @mbg.generated
     */
    private String creatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_examination_online.create_time
     *
     * @mbg.generated
     */
    private Long createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_examination_online.modifier_id
     *
     * @mbg.generated
     */
    private String modifierId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_examination_online.modify_time
     *
     * @mbg.generated
     */
    private Long modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_examination_online.ts
     *
     * @mbg.generated
     */
    private Long ts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_examination_online.dr
     *
     * @mbg.generated
     */
    private String dr;


    private String examinationCode;

    private String examinationDateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_examination_online.id
     *
     * @return the value of pro_elite_examination_online.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_examination_online.id
     *
     * @param id the value for pro_elite_examination_online.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_examination_online.employee_id
     *
     * @return the value of pro_elite_examination_online.employee_id
     *
     * @mbg.generated
     */
    public String getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_examination_online.employee_id
     *
     * @param employeeId the value for pro_elite_examination_online.employee_id
     *
     * @mbg.generated
     */
    public void setEmployeeId(String employeeId) {
        this.employeeId = employeeId == null ? null : employeeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_examination_online.employee_code
     *
     * @return the value of pro_elite_examination_online.employee_code
     *
     * @mbg.generated
     */
    public String getEmployeeCode() {
        return employeeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_examination_online.employee_code
     *
     * @param employeeCode the value for pro_elite_examination_online.employee_code
     *
     * @mbg.generated
     */
    public void setEmployeeCode(String employeeCode) {
        this.employeeCode = employeeCode == null ? null : employeeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_examination_online.relult_score
     *
     * @return the value of pro_elite_examination_online.relult_score
     *
     * @mbg.generated
     */
    public Integer getRelultScore() {
        return relultScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_examination_online.relult_score
     *
     * @param relultScore the value for pro_elite_examination_online.relult_score
     *
     * @mbg.generated
     */
    public void setRelultScore(Integer relultScore) {
        this.relultScore = relultScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_examination_online.pass_score
     *
     * @return the value of pro_elite_examination_online.pass_score
     *
     * @mbg.generated
     */
    public Integer getPassScore() {
        return passScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_examination_online.pass_score
     *
     * @param passScore the value for pro_elite_examination_online.pass_score
     *
     * @mbg.generated
     */
    public void setPassScore(Integer passScore) {
        this.passScore = passScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_examination_online.is_pass
     *
     * @return the value of pro_elite_examination_online.is_pass
     *
     * @mbg.generated
     */
    public String getIsPass() {
        return isPass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_examination_online.is_pass
     *
     * @param isPass the value for pro_elite_examination_online.is_pass
     *
     * @mbg.generated
     */
    public void setIsPass(String isPass) {
        this.isPass = isPass == null ? null : isPass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_examination_online.creator_id
     *
     * @return the value of pro_elite_examination_online.creator_id
     *
     * @mbg.generated
     */
    public String getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_examination_online.creator_id
     *
     * @param creatorId the value for pro_elite_examination_online.creator_id
     *
     * @mbg.generated
     */
    public void setCreatorId(String creatorId) {
        this.creatorId = creatorId == null ? null : creatorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_examination_online.create_time
     *
     * @return the value of pro_elite_examination_online.create_time
     *
     * @mbg.generated
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_examination_online.create_time
     *
     * @param createTime the value for pro_elite_examination_online.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_examination_online.modifier_id
     *
     * @return the value of pro_elite_examination_online.modifier_id
     *
     * @mbg.generated
     */
    public String getModifierId() {
        return modifierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_examination_online.modifier_id
     *
     * @param modifierId the value for pro_elite_examination_online.modifier_id
     *
     * @mbg.generated
     */
    public void setModifierId(String modifierId) {
        this.modifierId = modifierId == null ? null : modifierId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_examination_online.modify_time
     *
     * @return the value of pro_elite_examination_online.modify_time
     *
     * @mbg.generated
     */
    public Long getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_examination_online.modify_time
     *
     * @param modifyTime the value for pro_elite_examination_online.modify_time
     *
     * @mbg.generated
     */
    public void setModifyTime(Long modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_examination_online.ts
     *
     * @return the value of pro_elite_examination_online.ts
     *
     * @mbg.generated
     */
    public Long getTs() {
        return ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_examination_online.ts
     *
     * @param ts the value for pro_elite_examination_online.ts
     *
     * @mbg.generated
     */
    public void setTs(Long ts) {
        this.ts = ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_examination_online.dr
     *
     * @return the value of pro_elite_examination_online.dr
     *
     * @mbg.generated
     */
    public String getDr() {
        return dr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_examination_online.dr
     *
     * @param dr the value for pro_elite_examination_online.dr
     *
     * @mbg.generated
     */
    public void setDr(String dr) {
        this.dr = dr == null ? null : dr.trim();
    }

    public String getExaminationCode() {
        return examinationCode;
    }

    public void setExaminationCode(String examinationCode) {
        this.examinationCode = examinationCode;
    }

    public String getExaminationDateTime() {
        return examinationDateTime;
    }

    public void setExaminationDateTime(String examinationDateTime) {
        this.examinationDateTime = examinationDateTime;
    }
}