package models;

import java.util.Date;

public class ProEmployee {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_employee.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_employee.hht_member_id
     *
     * @mbg.generated
     */
    private String hhtMemberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_employee.company_id
     *
     * @mbg.generated
     */
    private String companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_employee.employee_no
     *
     * @mbg.generated
     */
    private String employeeNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_employee.employee_code
     *
     * @mbg.generated
     */
    private String employeeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_employee.employee_name
     *
     * @mbg.generated
     */
    private String employeeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_employee.nationality_id
     *
     * @mbg.generated
     */
    private String nationalityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_employee.paper_type_id
     *
     * @mbg.generated
     */
    private String paperTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_employee.paper_no
     *
     * @mbg.generated
     */
    private String paperNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_employee.birthday
     *
     * @mbg.generated
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_employee.gender
     *
     * @mbg.generated
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_employee.mobile_no
     *
     * @mbg.generated
     */
    private String mobileNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_employee.tel_no
     *
     * @mbg.generated
     */
    private String telNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_employee.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_employee.home_addr
     *
     * @mbg.generated
     */
    private String homeAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_employee.head_portrait
     *
     * @mbg.generated
     */
    private String headPortrait;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_employee.first_entry_time
     *
     * @mbg.generated
     */
    private Long firstEntryTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_employee.last_entry_time
     *
     * @mbg.generated
     */
    private Long lastEntryTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_employee.last_leave_time
     *
     * @mbg.generated
     */
    private Long lastLeaveTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_employee.enable
     *
     * @mbg.generated
     */
    private String enable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_employee.creator_id
     *
     * @mbg.generated
     */
    private String creatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_employee.modifier_id
     *
     * @mbg.generated
     */
    private String modifierId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_employee.locked
     *
     * @mbg.generated
     */
    private String locked;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_employee.locked_reason
     *
     * @mbg.generated
     */
    private String lockedReason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_employee.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_employee.dr
     *
     * @mbg.generated
     */
    private String dr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_employee.ts
     *
     * @mbg.generated
     */
    private Long ts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_employee.version
     *
     * @mbg.generated
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_employee.id
     *
     * @return the value of pro_employee.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_employee.id
     *
     * @param id the value for pro_employee.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_employee.hht_member_id
     *
     * @return the value of pro_employee.hht_member_id
     *
     * @mbg.generated
     */
    public String getHhtMemberId() {
        return hhtMemberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_employee.hht_member_id
     *
     * @param hhtMemberId the value for pro_employee.hht_member_id
     *
     * @mbg.generated
     */
    public void setHhtMemberId(String hhtMemberId) {
        this.hhtMemberId = hhtMemberId == null ? null : hhtMemberId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_employee.company_id
     *
     * @return the value of pro_employee.company_id
     *
     * @mbg.generated
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_employee.company_id
     *
     * @param companyId the value for pro_employee.company_id
     *
     * @mbg.generated
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_employee.employee_no
     *
     * @return the value of pro_employee.employee_no
     *
     * @mbg.generated
     */
    public String getEmployeeNo() {
        return employeeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_employee.employee_no
     *
     * @param employeeNo the value for pro_employee.employee_no
     *
     * @mbg.generated
     */
    public void setEmployeeNo(String employeeNo) {
        this.employeeNo = employeeNo == null ? null : employeeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_employee.employee_code
     *
     * @return the value of pro_employee.employee_code
     *
     * @mbg.generated
     */
    public String getEmployeeCode() {
        return employeeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_employee.employee_code
     *
     * @param employeeCode the value for pro_employee.employee_code
     *
     * @mbg.generated
     */
    public void setEmployeeCode(String employeeCode) {
        this.employeeCode = employeeCode == null ? null : employeeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_employee.employee_name
     *
     * @return the value of pro_employee.employee_name
     *
     * @mbg.generated
     */
    public String getEmployeeName() {
        return employeeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_employee.employee_name
     *
     * @param employeeName the value for pro_employee.employee_name
     *
     * @mbg.generated
     */
    public void setEmployeeName(String employeeName) {
        this.employeeName = employeeName == null ? null : employeeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_employee.nationality_id
     *
     * @return the value of pro_employee.nationality_id
     *
     * @mbg.generated
     */
    public String getNationalityId() {
        return nationalityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_employee.nationality_id
     *
     * @param nationalityId the value for pro_employee.nationality_id
     *
     * @mbg.generated
     */
    public void setNationalityId(String nationalityId) {
        this.nationalityId = nationalityId == null ? null : nationalityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_employee.paper_type_id
     *
     * @return the value of pro_employee.paper_type_id
     *
     * @mbg.generated
     */
    public String getPaperTypeId() {
        return paperTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_employee.paper_type_id
     *
     * @param paperTypeId the value for pro_employee.paper_type_id
     *
     * @mbg.generated
     */
    public void setPaperTypeId(String paperTypeId) {
        this.paperTypeId = paperTypeId == null ? null : paperTypeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_employee.paper_no
     *
     * @return the value of pro_employee.paper_no
     *
     * @mbg.generated
     */
    public String getPaperNo() {
        return paperNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_employee.paper_no
     *
     * @param paperNo the value for pro_employee.paper_no
     *
     * @mbg.generated
     */
    public void setPaperNo(String paperNo) {
        this.paperNo = paperNo == null ? null : paperNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_employee.birthday
     *
     * @return the value of pro_employee.birthday
     *
     * @mbg.generated
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_employee.birthday
     *
     * @param birthday the value for pro_employee.birthday
     *
     * @mbg.generated
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_employee.gender
     *
     * @return the value of pro_employee.gender
     *
     * @mbg.generated
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_employee.gender
     *
     * @param gender the value for pro_employee.gender
     *
     * @mbg.generated
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_employee.mobile_no
     *
     * @return the value of pro_employee.mobile_no
     *
     * @mbg.generated
     */
    public String getMobileNo() {
        return mobileNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_employee.mobile_no
     *
     * @param mobileNo the value for pro_employee.mobile_no
     *
     * @mbg.generated
     */
    public void setMobileNo(String mobileNo) {
        this.mobileNo = mobileNo == null ? null : mobileNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_employee.tel_no
     *
     * @return the value of pro_employee.tel_no
     *
     * @mbg.generated
     */
    public String getTelNo() {
        return telNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_employee.tel_no
     *
     * @param telNo the value for pro_employee.tel_no
     *
     * @mbg.generated
     */
    public void setTelNo(String telNo) {
        this.telNo = telNo == null ? null : telNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_employee.email
     *
     * @return the value of pro_employee.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_employee.email
     *
     * @param email the value for pro_employee.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_employee.home_addr
     *
     * @return the value of pro_employee.home_addr
     *
     * @mbg.generated
     */
    public String getHomeAddr() {
        return homeAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_employee.home_addr
     *
     * @param homeAddr the value for pro_employee.home_addr
     *
     * @mbg.generated
     */
    public void setHomeAddr(String homeAddr) {
        this.homeAddr = homeAddr == null ? null : homeAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_employee.head_portrait
     *
     * @return the value of pro_employee.head_portrait
     *
     * @mbg.generated
     */
    public String getHeadPortrait() {
        return headPortrait;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_employee.head_portrait
     *
     * @param headPortrait the value for pro_employee.head_portrait
     *
     * @mbg.generated
     */
    public void setHeadPortrait(String headPortrait) {
        this.headPortrait = headPortrait == null ? null : headPortrait.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_employee.first_entry_time
     *
     * @return the value of pro_employee.first_entry_time
     *
     * @mbg.generated
     */
    public Long getFirstEntryTime() {
        return firstEntryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_employee.first_entry_time
     *
     * @param firstEntryTime the value for pro_employee.first_entry_time
     *
     * @mbg.generated
     */
    public void setFirstEntryTime(Long firstEntryTime) {
        this.firstEntryTime = firstEntryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_employee.last_entry_time
     *
     * @return the value of pro_employee.last_entry_time
     *
     * @mbg.generated
     */
    public Long getLastEntryTime() {
        return lastEntryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_employee.last_entry_time
     *
     * @param lastEntryTime the value for pro_employee.last_entry_time
     *
     * @mbg.generated
     */
    public void setLastEntryTime(Long lastEntryTime) {
        this.lastEntryTime = lastEntryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_employee.last_leave_time
     *
     * @return the value of pro_employee.last_leave_time
     *
     * @mbg.generated
     */
    public Long getLastLeaveTime() {
        return lastLeaveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_employee.last_leave_time
     *
     * @param lastLeaveTime the value for pro_employee.last_leave_time
     *
     * @mbg.generated
     */
    public void setLastLeaveTime(Long lastLeaveTime) {
        this.lastLeaveTime = lastLeaveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_employee.enable
     *
     * @return the value of pro_employee.enable
     *
     * @mbg.generated
     */
    public String getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_employee.enable
     *
     * @param enable the value for pro_employee.enable
     *
     * @mbg.generated
     */
    public void setEnable(String enable) {
        this.enable = enable == null ? null : enable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_employee.creator_id
     *
     * @return the value of pro_employee.creator_id
     *
     * @mbg.generated
     */
    public String getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_employee.creator_id
     *
     * @param creatorId the value for pro_employee.creator_id
     *
     * @mbg.generated
     */
    public void setCreatorId(String creatorId) {
        this.creatorId = creatorId == null ? null : creatorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_employee.modifier_id
     *
     * @return the value of pro_employee.modifier_id
     *
     * @mbg.generated
     */
    public String getModifierId() {
        return modifierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_employee.modifier_id
     *
     * @param modifierId the value for pro_employee.modifier_id
     *
     * @mbg.generated
     */
    public void setModifierId(String modifierId) {
        this.modifierId = modifierId == null ? null : modifierId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_employee.locked
     *
     * @return the value of pro_employee.locked
     *
     * @mbg.generated
     */
    public String getLocked() {
        return locked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_employee.locked
     *
     * @param locked the value for pro_employee.locked
     *
     * @mbg.generated
     */
    public void setLocked(String locked) {
        this.locked = locked == null ? null : locked.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_employee.locked_reason
     *
     * @return the value of pro_employee.locked_reason
     *
     * @mbg.generated
     */
    public String getLockedReason() {
        return lockedReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_employee.locked_reason
     *
     * @param lockedReason the value for pro_employee.locked_reason
     *
     * @mbg.generated
     */
    public void setLockedReason(String lockedReason) {
        this.lockedReason = lockedReason == null ? null : lockedReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_employee.remark
     *
     * @return the value of pro_employee.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_employee.remark
     *
     * @param remark the value for pro_employee.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_employee.dr
     *
     * @return the value of pro_employee.dr
     *
     * @mbg.generated
     */
    public String getDr() {
        return dr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_employee.dr
     *
     * @param dr the value for pro_employee.dr
     *
     * @mbg.generated
     */
    public void setDr(String dr) {
        this.dr = dr == null ? null : dr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_employee.ts
     *
     * @return the value of pro_employee.ts
     *
     * @mbg.generated
     */
    public Long getTs() {
        return ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_employee.ts
     *
     * @param ts the value for pro_employee.ts
     *
     * @mbg.generated
     */
    public void setTs(Long ts) {
        this.ts = ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_employee.version
     *
     * @return the value of pro_employee.version
     *
     * @mbg.generated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_employee.version
     *
     * @param version the value for pro_employee.version
     *
     * @mbg.generated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}