package models;

public class ProEmployeePosition {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_employee_position.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_employee_position.company_id
     *
     * @mbg.generated
     */
    private String companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_employee_position.employee_id
     *
     * @mbg.generated
     */
    private String employeeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_employee_position.position_id
     *
     * @mbg.generated
     */
    private String positionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_employee_position.shop_id
     *
     * @mbg.generated
     */
    private String shopId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_employee_position.start_time
     *
     * @mbg.generated
     */
    private Long startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_employee_position.end_time
     *
     * @mbg.generated
     */
    private Long endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_employee_position.default_position
     *
     * @mbg.generated
     */
    private String defaultPosition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_employee_position.enable
     *
     * @mbg.generated
     */
    private String enable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_employee_position.create_time
     *
     * @mbg.generated
     */
    private Long createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_employee_position.creator_id
     *
     * @mbg.generated
     */
    private String creatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_employee_position.modify_time
     *
     * @mbg.generated
     */
    private Long modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_employee_position.modifier_id
     *
     * @mbg.generated
     */
    private String modifierId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_employee_position.dr
     *
     * @mbg.generated
     */
    private String dr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_employee_position.ts
     *
     * @mbg.generated
     */
    private Long ts;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_employee_position.id
     *
     * @return the value of pro_employee_position.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_employee_position.id
     *
     * @param id the value for pro_employee_position.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_employee_position.company_id
     *
     * @return the value of pro_employee_position.company_id
     *
     * @mbg.generated
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_employee_position.company_id
     *
     * @param companyId the value for pro_employee_position.company_id
     *
     * @mbg.generated
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_employee_position.employee_id
     *
     * @return the value of pro_employee_position.employee_id
     *
     * @mbg.generated
     */
    public String getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_employee_position.employee_id
     *
     * @param employeeId the value for pro_employee_position.employee_id
     *
     * @mbg.generated
     */
    public void setEmployeeId(String employeeId) {
        this.employeeId = employeeId == null ? null : employeeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_employee_position.position_id
     *
     * @return the value of pro_employee_position.position_id
     *
     * @mbg.generated
     */
    public String getPositionId() {
        return positionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_employee_position.position_id
     *
     * @param positionId the value for pro_employee_position.position_id
     *
     * @mbg.generated
     */
    public void setPositionId(String positionId) {
        this.positionId = positionId == null ? null : positionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_employee_position.shop_id
     *
     * @return the value of pro_employee_position.shop_id
     *
     * @mbg.generated
     */
    public String getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_employee_position.shop_id
     *
     * @param shopId the value for pro_employee_position.shop_id
     *
     * @mbg.generated
     */
    public void setShopId(String shopId) {
        this.shopId = shopId == null ? null : shopId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_employee_position.start_time
     *
     * @return the value of pro_employee_position.start_time
     *
     * @mbg.generated
     */
    public Long getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_employee_position.start_time
     *
     * @param startTime the value for pro_employee_position.start_time
     *
     * @mbg.generated
     */
    public void setStartTime(Long startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_employee_position.end_time
     *
     * @return the value of pro_employee_position.end_time
     *
     * @mbg.generated
     */
    public Long getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_employee_position.end_time
     *
     * @param endTime the value for pro_employee_position.end_time
     *
     * @mbg.generated
     */
    public void setEndTime(Long endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_employee_position.default_position
     *
     * @return the value of pro_employee_position.default_position
     *
     * @mbg.generated
     */
    public String getDefaultPosition() {
        return defaultPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_employee_position.default_position
     *
     * @param defaultPosition the value for pro_employee_position.default_position
     *
     * @mbg.generated
     */
    public void setDefaultPosition(String defaultPosition) {
        this.defaultPosition = defaultPosition == null ? null : defaultPosition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_employee_position.enable
     *
     * @return the value of pro_employee_position.enable
     *
     * @mbg.generated
     */
    public String getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_employee_position.enable
     *
     * @param enable the value for pro_employee_position.enable
     *
     * @mbg.generated
     */
    public void setEnable(String enable) {
        this.enable = enable == null ? null : enable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_employee_position.create_time
     *
     * @return the value of pro_employee_position.create_time
     *
     * @mbg.generated
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_employee_position.create_time
     *
     * @param createTime the value for pro_employee_position.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_employee_position.creator_id
     *
     * @return the value of pro_employee_position.creator_id
     *
     * @mbg.generated
     */
    public String getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_employee_position.creator_id
     *
     * @param creatorId the value for pro_employee_position.creator_id
     *
     * @mbg.generated
     */
    public void setCreatorId(String creatorId) {
        this.creatorId = creatorId == null ? null : creatorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_employee_position.modify_time
     *
     * @return the value of pro_employee_position.modify_time
     *
     * @mbg.generated
     */
    public Long getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_employee_position.modify_time
     *
     * @param modifyTime the value for pro_employee_position.modify_time
     *
     * @mbg.generated
     */
    public void setModifyTime(Long modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_employee_position.modifier_id
     *
     * @return the value of pro_employee_position.modifier_id
     *
     * @mbg.generated
     */
    public String getModifierId() {
        return modifierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_employee_position.modifier_id
     *
     * @param modifierId the value for pro_employee_position.modifier_id
     *
     * @mbg.generated
     */
    public void setModifierId(String modifierId) {
        this.modifierId = modifierId == null ? null : modifierId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_employee_position.dr
     *
     * @return the value of pro_employee_position.dr
     *
     * @mbg.generated
     */
    public String getDr() {
        return dr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_employee_position.dr
     *
     * @param dr the value for pro_employee_position.dr
     *
     * @mbg.generated
     */
    public void setDr(String dr) {
        this.dr = dr == null ? null : dr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_employee_position.ts
     *
     * @return the value of pro_employee_position.ts
     *
     * @mbg.generated
     */
    public Long getTs() {
        return ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_employee_position.ts
     *
     * @param ts the value for pro_employee_position.ts
     *
     * @mbg.generated
     */
    public void setTs(Long ts) {
        this.ts = ts;
    }
}