package models;

public class ProEliteTestRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_test_record.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_test_record.test_url
     *
     * @mbg.generated
     */
    private String testUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_test_record.test_report_url
     *
     * @mbg.generated
     */
    private String testReportUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_test_record.test_result
     *
     * @mbg.generated
     */
    private String testResult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_test_record.score
     *
     * @mbg.generated
     */
    private String score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_test_record.enable
     *
     * @mbg.generated
     */
    private String enable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_test_record.creator_id
     *
     * @mbg.generated
     */
    private String creatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_test_record.create_time
     *
     * @mbg.generated
     */
    private Long createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_test_record.modifier_id
     *
     * @mbg.generated
     */
    private String modifierId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_test_record.modify_time
     *
     * @mbg.generated
     */
    private Long modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_test_record.ts
     *
     * @mbg.generated
     */
    private Long ts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_test_record.dr
     *
     * @mbg.generated
     */
    private String dr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_test_record.employee_id
     *
     * @mbg.generated
     */
    private String employeeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_test_record.test_once_id
     *
     * @mbg.generated
     */
    private String testOnceId;


    private String testEndTime;

    private String isTask;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_test_record.id
     *
     * @return the value of pro_elite_test_record.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_test_record.id
     *
     * @param id the value for pro_elite_test_record.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_test_record.test_url
     *
     * @return the value of pro_elite_test_record.test_url
     *
     * @mbg.generated
     */
    public String getTestUrl() {
        return testUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_test_record.test_url
     *
     * @param testUrl the value for pro_elite_test_record.test_url
     *
     * @mbg.generated
     */
    public void setTestUrl(String testUrl) {
        this.testUrl = testUrl == null ? null : testUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_test_record.test_report_url
     *
     * @return the value of pro_elite_test_record.test_report_url
     *
     * @mbg.generated
     */
    public String getTestReportUrl() {
        return testReportUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_test_record.test_report_url
     *
     * @param testReportUrl the value for pro_elite_test_record.test_report_url
     *
     * @mbg.generated
     */
    public void setTestReportUrl(String testReportUrl) {
        this.testReportUrl = testReportUrl == null ? null : testReportUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_test_record.test_result
     *
     * @return the value of pro_elite_test_record.test_result
     *
     * @mbg.generated
     */
    public String getTestResult() {
        return testResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_test_record.test_result
     *
     * @param testResult the value for pro_elite_test_record.test_result
     *
     * @mbg.generated
     */
    public void setTestResult(String testResult) {
        this.testResult = testResult == null ? null : testResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_test_record.score
     *
     * @return the value of pro_elite_test_record.score
     *
     * @mbg.generated
     */
    public String getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_test_record.score
     *
     * @param score the value for pro_elite_test_record.score
     *
     * @mbg.generated
     */
    public void setScore(String score) {
        this.score = score == null ? null : score.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_test_record.enable
     *
     * @return the value of pro_elite_test_record.enable
     *
     * @mbg.generated
     */
    public String getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_test_record.enable
     *
     * @param enable the value for pro_elite_test_record.enable
     *
     * @mbg.generated
     */
    public void setEnable(String enable) {
        this.enable = enable == null ? null : enable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_test_record.creator_id
     *
     * @return the value of pro_elite_test_record.creator_id
     *
     * @mbg.generated
     */
    public String getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_test_record.creator_id
     *
     * @param creatorId the value for pro_elite_test_record.creator_id
     *
     * @mbg.generated
     */
    public void setCreatorId(String creatorId) {
        this.creatorId = creatorId == null ? null : creatorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_test_record.create_time
     *
     * @return the value of pro_elite_test_record.create_time
     *
     * @mbg.generated
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_test_record.create_time
     *
     * @param createTime the value for pro_elite_test_record.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_test_record.modifier_id
     *
     * @return the value of pro_elite_test_record.modifier_id
     *
     * @mbg.generated
     */
    public String getModifierId() {
        return modifierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_test_record.modifier_id
     *
     * @param modifierId the value for pro_elite_test_record.modifier_id
     *
     * @mbg.generated
     */
    public void setModifierId(String modifierId) {
        this.modifierId = modifierId == null ? null : modifierId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_test_record.modify_time
     *
     * @return the value of pro_elite_test_record.modify_time
     *
     * @mbg.generated
     */
    public Long getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_test_record.modify_time
     *
     * @param modifyTime the value for pro_elite_test_record.modify_time
     *
     * @mbg.generated
     */
    public void setModifyTime(Long modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_test_record.ts
     *
     * @return the value of pro_elite_test_record.ts
     *
     * @mbg.generated
     */
    public Long getTs() {
        return ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_test_record.ts
     *
     * @param ts the value for pro_elite_test_record.ts
     *
     * @mbg.generated
     */
    public void setTs(Long ts) {
        this.ts = ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_test_record.dr
     *
     * @return the value of pro_elite_test_record.dr
     *
     * @mbg.generated
     */
    public String getDr() {
        return dr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_test_record.dr
     *
     * @param dr the value for pro_elite_test_record.dr
     *
     * @mbg.generated
     */
    public void setDr(String dr) {
        this.dr = dr == null ? null : dr.trim();
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_test_record.test_once_id
     *
     * @return the value of pro_elite_test_record.test_once_id
     *
     * @mbg.generated
     */
    public String getTestOnceId() {
        return testOnceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_test_record.test_once_id
     *
     * @param testOnceId the value for pro_elite_test_record.test_once_id
     *
     * @mbg.generated
     */
    public void setTestOnceId(String testOnceId) {
        this.testOnceId = testOnceId == null ? null : testOnceId.trim();
    }

    public String getEmployeeCode() {
        return employeeCode;
    }

    public void setEmployeeCode(String employeeCode) {
        this.employeeCode = employeeCode;
    }

    public String getTestEndTime() {
        return testEndTime;
    }

    public void setTestEndTime(String testEndTime) {
        this.testEndTime = testEndTime;
    }

    public String getIsTask() {
        return isTask;
    }

    public void setIsTask(String isTask) {
        this.isTask = isTask;
    }
}