package models;

import java.math.BigDecimal;

public class ProEliteTrainCost {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_train_cost.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_train_cost.evaluating_manager_cost
     *
     * @mbg.generated
     */
    private BigDecimal evaluatingManagerCost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_train_cost.evaluating_employee_cost
     *
     * @mbg.generated
     */
    private BigDecimal evaluatingEmployeeCost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_train_cost.lobby_manager_cost
     *
     * @mbg.generated
     */
    private BigDecimal lobbyManagerCost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_train_cost.lobby_employee_cost
     *
     * @mbg.generated
     */
    private BigDecimal lobbyEmployeeCost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_train_cost.reserve_manager_cost
     *
     * @mbg.generated
     */
    private BigDecimal reserveManagerCost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_train_cost.reserve_employee_cost
     *
     * @mbg.generated
     */
    private BigDecimal reserveEmployeeCost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_train_cost.reserve_manager_amerce
     *
     * @mbg.generated
     */
    private BigDecimal reserveManagerAmerce;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_train_cost.reserve_employee_amerce
     *
     * @mbg.generated
     */
    private BigDecimal reserveEmployeeAmerce;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_train_cost.creator_id
     *
     * @mbg.generated
     */
    private String creatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_train_cost.create_time
     *
     * @mbg.generated
     */
    private Long createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_train_cost.modifier_id
     *
     * @mbg.generated
     */
    private String modifierId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_train_cost.modify_time
     *
     * @mbg.generated
     */
    private Long modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_train_cost.ts
     *
     * @mbg.generated
     */
    private Long ts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_train_cost.dr
     *
     * @mbg.generated
     */
    private String dr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_train_cost.id
     *
     * @return the value of pro_elite_train_cost.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_train_cost.id
     *
     * @param id the value for pro_elite_train_cost.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_train_cost.evaluating_manager_cost
     *
     * @return the value of pro_elite_train_cost.evaluating_manager_cost
     *
     * @mbg.generated
     */
    public BigDecimal getEvaluatingManagerCost() {
        return evaluatingManagerCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_train_cost.evaluating_manager_cost
     *
     * @param evaluatingManagerCost the value for pro_elite_train_cost.evaluating_manager_cost
     *
     * @mbg.generated
     */
    public void setEvaluatingManagerCost(BigDecimal evaluatingManagerCost) {
        this.evaluatingManagerCost = evaluatingManagerCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_train_cost.evaluating_employee_cost
     *
     * @return the value of pro_elite_train_cost.evaluating_employee_cost
     *
     * @mbg.generated
     */
    public BigDecimal getEvaluatingEmployeeCost() {
        return evaluatingEmployeeCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_train_cost.evaluating_employee_cost
     *
     * @param evaluatingEmployeeCost the value for pro_elite_train_cost.evaluating_employee_cost
     *
     * @mbg.generated
     */
    public void setEvaluatingEmployeeCost(BigDecimal evaluatingEmployeeCost) {
        this.evaluatingEmployeeCost = evaluatingEmployeeCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_train_cost.lobby_manager_cost
     *
     * @return the value of pro_elite_train_cost.lobby_manager_cost
     *
     * @mbg.generated
     */
    public BigDecimal getLobbyManagerCost() {
        return lobbyManagerCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_train_cost.lobby_manager_cost
     *
     * @param lobbyManagerCost the value for pro_elite_train_cost.lobby_manager_cost
     *
     * @mbg.generated
     */
    public void setLobbyManagerCost(BigDecimal lobbyManagerCost) {
        this.lobbyManagerCost = lobbyManagerCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_train_cost.lobby_employee_cost
     *
     * @return the value of pro_elite_train_cost.lobby_employee_cost
     *
     * @mbg.generated
     */
    public BigDecimal getLobbyEmployeeCost() {
        return lobbyEmployeeCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_train_cost.lobby_employee_cost
     *
     * @param lobbyEmployeeCost the value for pro_elite_train_cost.lobby_employee_cost
     *
     * @mbg.generated
     */
    public void setLobbyEmployeeCost(BigDecimal lobbyEmployeeCost) {
        this.lobbyEmployeeCost = lobbyEmployeeCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_train_cost.reserve_manager_cost
     *
     * @return the value of pro_elite_train_cost.reserve_manager_cost
     *
     * @mbg.generated
     */
    public BigDecimal getReserveManagerCost() {
        return reserveManagerCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_train_cost.reserve_manager_cost
     *
     * @param reserveManagerCost the value for pro_elite_train_cost.reserve_manager_cost
     *
     * @mbg.generated
     */
    public void setReserveManagerCost(BigDecimal reserveManagerCost) {
        this.reserveManagerCost = reserveManagerCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_train_cost.reserve_employee_cost
     *
     * @return the value of pro_elite_train_cost.reserve_employee_cost
     *
     * @mbg.generated
     */
    public BigDecimal getReserveEmployeeCost() {
        return reserveEmployeeCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_train_cost.reserve_employee_cost
     *
     * @param reserveEmployeeCost the value for pro_elite_train_cost.reserve_employee_cost
     *
     * @mbg.generated
     */
    public void setReserveEmployeeCost(BigDecimal reserveEmployeeCost) {
        this.reserveEmployeeCost = reserveEmployeeCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_train_cost.reserve_manager_amerce
     *
     * @return the value of pro_elite_train_cost.reserve_manager_amerce
     *
     * @mbg.generated
     */
    public BigDecimal getReserveManagerAmerce() {
        return reserveManagerAmerce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_train_cost.reserve_manager_amerce
     *
     * @param reserveManagerAmerce the value for pro_elite_train_cost.reserve_manager_amerce
     *
     * @mbg.generated
     */
    public void setReserveManagerAmerce(BigDecimal reserveManagerAmerce) {
        this.reserveManagerAmerce = reserveManagerAmerce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_train_cost.reserve_employee_amerce
     *
     * @return the value of pro_elite_train_cost.reserve_employee_amerce
     *
     * @mbg.generated
     */
    public BigDecimal getReserveEmployeeAmerce() {
        return reserveEmployeeAmerce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_train_cost.reserve_employee_amerce
     *
     * @param reserveEmployeeAmerce the value for pro_elite_train_cost.reserve_employee_amerce
     *
     * @mbg.generated
     */
    public void setReserveEmployeeAmerce(BigDecimal reserveEmployeeAmerce) {
        this.reserveEmployeeAmerce = reserveEmployeeAmerce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_train_cost.creator_id
     *
     * @return the value of pro_elite_train_cost.creator_id
     *
     * @mbg.generated
     */
    public String getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_train_cost.creator_id
     *
     * @param creatorId the value for pro_elite_train_cost.creator_id
     *
     * @mbg.generated
     */
    public void setCreatorId(String creatorId) {
        this.creatorId = creatorId == null ? null : creatorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_train_cost.create_time
     *
     * @return the value of pro_elite_train_cost.create_time
     *
     * @mbg.generated
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_train_cost.create_time
     *
     * @param createTime the value for pro_elite_train_cost.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_train_cost.modifier_id
     *
     * @return the value of pro_elite_train_cost.modifier_id
     *
     * @mbg.generated
     */
    public String getModifierId() {
        return modifierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_train_cost.modifier_id
     *
     * @param modifierId the value for pro_elite_train_cost.modifier_id
     *
     * @mbg.generated
     */
    public void setModifierId(String modifierId) {
        this.modifierId = modifierId == null ? null : modifierId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_train_cost.modify_time
     *
     * @return the value of pro_elite_train_cost.modify_time
     *
     * @mbg.generated
     */
    public Long getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_train_cost.modify_time
     *
     * @param modifyTime the value for pro_elite_train_cost.modify_time
     *
     * @mbg.generated
     */
    public void setModifyTime(Long modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_train_cost.ts
     *
     * @return the value of pro_elite_train_cost.ts
     *
     * @mbg.generated
     */
    public Long getTs() {
        return ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_train_cost.ts
     *
     * @param ts the value for pro_elite_train_cost.ts
     *
     * @mbg.generated
     */
    public void setTs(Long ts) {
        this.ts = ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_train_cost.dr
     *
     * @return the value of pro_elite_train_cost.dr
     *
     * @mbg.generated
     */
    public String getDr() {
        return dr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_train_cost.dr
     *
     * @param dr the value for pro_elite_train_cost.dr
     *
     * @mbg.generated
     */
    public void setDr(String dr) {
        this.dr = dr == null ? null : dr.trim();
    }
}