package models;

import java.math.BigDecimal;

public class ProEliteClassPerson {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_class_person.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_class_person.employee_id
     *
     * @mbg.generated
     */
    private String employeeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_class_person.employee_code
     *
     * @mbg.generated
     */
    private String employeeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_class_person.train_end
     *
     * @mbg.generated
     */
    private Long trainEnd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_class_person.result
     *
     * @mbg.generated
     */
    private String result;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_class_person.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_class_person.creator_id
     *
     * @mbg.generated
     */
    private String creatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_class_person.create_time
     *
     * @mbg.generated
     */
    private Long createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_class_person.modifier_id
     *
     * @mbg.generated
     */
    private String modifierId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_class_person.modify_time
     *
     * @mbg.generated
     */
    private Long modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_class_person.ts
     *
     * @mbg.generated
     */
    private Long ts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_class_person.dr
     *
     * @mbg.generated
     */
    private String dr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_class_person.class_id
     *
     * @mbg.generated
     */
    private String classId;

    
    private Long groomTime;

    private BigDecimal managerAmerce;

    private BigDecimal employeeAmerce;

    private BigDecimal employeeCost;

    private BigDecimal managerCost;

    private String shopId;

    private String lobbyType;

    private String lobbyRemark;

    private  String score;

    public String getLobbyType() {
        return lobbyType;
    }

    public void setLobbyType(String lobbyType) {
        this.lobbyType = lobbyType;
    }

    public String getLobbyRemark() {
        return lobbyRemark;
    }

    public void setLobbyRemark(String lobbyRemark) {
        this.lobbyRemark = lobbyRemark;
    }

    public String getScore() {
        return score;
    }

    public void setScore(String score) {
        this.score = score;
    }

    public Long getGroomTime() {
        return groomTime;
    }

    public void setGroomTime(Long groomTime) {
        this.groomTime = groomTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_class_person.id
     *
     * @return the value of pro_elite_class_person.id
     *
     * @mbg.generated
     */

    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_class_person.id
     *
     * @param id the value for pro_elite_class_person.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_class_person.employee_id
     *
     * @return the value of pro_elite_class_person.employee_id
     *
     * @mbg.generated
     */
    public String getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_class_person.employee_id
     *
     * @param employeeId the value for pro_elite_class_person.employee_id
     *
     * @mbg.generated
     */
    public void setEmployeeId(String employeeId) {
        this.employeeId = employeeId == null ? null : employeeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_class_person.employee_code
     *
     * @return the value of pro_elite_class_person.employee_code
     *
     * @mbg.generated
     */
    public String getEmployeeCode() {
        return employeeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_class_person.employee_code
     *
     * @param employeeCode the value for pro_elite_class_person.employee_code
     *
     * @mbg.generated
     */
    public void setEmployeeCode(String employeeCode) {
        this.employeeCode = employeeCode == null ? null : employeeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_class_person.train_end
     *
     * @return the value of pro_elite_class_person.train_end
     *
     * @mbg.generated
     */
    public Long getTrainEnd() {
        return trainEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_class_person.train_end
     *
     * @param trainEnd the value for pro_elite_class_person.train_end
     *
     * @mbg.generated
     */
    public void setTrainEnd(Long trainEnd) {
        this.trainEnd = trainEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_class_person.result
     *
     * @return the value of pro_elite_class_person.result
     *
     * @mbg.generated
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_class_person.result
     *
     * @param result the value for pro_elite_class_person.result
     *
     * @mbg.generated
     */
    public void setResult(String result) {
        this.result = result == null ? null : result.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_class_person.remark
     *
     * @return the value of pro_elite_class_person.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_class_person.remark
     *
     * @param remark the value for pro_elite_class_person.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_class_person.creator_id
     *
     * @return the value of pro_elite_class_person.creator_id
     *
     * @mbg.generated
     */
    public String getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_class_person.creator_id
     *
     * @param creatorId the value for pro_elite_class_person.creator_id
     *
     * @mbg.generated
     */
    public void setCreatorId(String creatorId) {
        this.creatorId = creatorId == null ? null : creatorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_class_person.create_time
     *
     * @return the value of pro_elite_class_person.create_time
     *
     * @mbg.generated
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_class_person.create_time
     *
     * @param createTime the value for pro_elite_class_person.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_class_person.modifier_id
     *
     * @return the value of pro_elite_class_person.modifier_id
     *
     * @mbg.generated
     */
    public String getModifierId() {
        return modifierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_class_person.modifier_id
     *
     * @param modifierId the value for pro_elite_class_person.modifier_id
     *
     * @mbg.generated
     */
    public void setModifierId(String modifierId) {
        this.modifierId = modifierId == null ? null : modifierId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_class_person.modify_time
     *
     * @return the value of pro_elite_class_person.modify_time
     *
     * @mbg.generated
     */
    public Long getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_class_person.modify_time
     *
     * @param modifyTime the value for pro_elite_class_person.modify_time
     *
     * @mbg.generated
     */
    public void setModifyTime(Long modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_class_person.ts
     *
     * @return the value of pro_elite_class_person.ts
     *
     * @mbg.generated
     */
    public Long getTs() {
        return ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_class_person.ts
     *
     * @param ts the value for pro_elite_class_person.ts
     *
     * @mbg.generated
     */
    public void setTs(Long ts) {
        this.ts = ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_class_person.dr
     *
     * @return the value of pro_elite_class_person.dr
     *
     * @mbg.generated
     */
    public String getDr() {
        return dr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_class_person.dr
     *
     * @param dr the value for pro_elite_class_person.dr
     *
     * @mbg.generated
     */
    public void setDr(String dr) {
        this.dr = dr == null ? null : dr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_class_person.class_id
     *
     * @return the value of pro_elite_class_person.class_id
     *
     * @mbg.generated
     */
    public String getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_class_person.class_id
     *
     * @param classId the value for pro_elite_class_person.class_id
     *
     * @mbg.generated
     */
    public void setClassId(String classId) {
        this.classId = classId == null ? null : classId.trim();
    }

    public BigDecimal getManagerAmerce() {
        return managerAmerce;
    }

    public void setManagerAmerce(BigDecimal managerAmerce) {
        this.managerAmerce = managerAmerce;
    }

    public BigDecimal getEmployeeAmerce() {
        return employeeAmerce;
    }

    public void setEmployeeAmerce(BigDecimal employeeAmerce) {
        this.employeeAmerce = employeeAmerce;
    }

    public BigDecimal getEmployeeCost() {
        return employeeCost;
    }

    public void setEmployeeCost(BigDecimal employeeCost) {
        this.employeeCost = employeeCost;
    }

    public BigDecimal getManagerCost() {
        return managerCost;
    }

    public void setManagerCost(BigDecimal managerCost) {
        this.managerCost = managerCost;
    }

    public String getShopId() {
        return shopId;
    }

    public void setShopId(String shopId) {
        this.shopId = shopId;
    }
}