package models;

public class ProEliteNoticeRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_notice_record.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_notice_record.notice_name
     *
     * @mbg.generated
     */
    private String noticeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_notice_record.notice_text
     *
     * @mbg.generated
     */
    private String noticeText;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_notice_record.is_read
     *
     * @mbg.generated
     */
    private String isRead;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_notice_record.employee_id
     *
     * @mbg.generated
     */
    private String employeeCode;

    private String employeeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_notice_record.creator_id
     *
     * @mbg.generated
     */
    private String creatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_notice_record.create_time
     *
     * @mbg.generated
     */
    private Long createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_notice_record.ts
     *
     * @mbg.generated
     */
    private Long ts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_elite_notice_record.dr
     *
     * @mbg.generated
     */
    private String dr;


    private String noticeCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_notice_record.id
     *
     * @return the value of pro_elite_notice_record.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_notice_record.id
     *
     * @param id the value for pro_elite_notice_record.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_notice_record.notice_name
     *
     * @return the value of pro_elite_notice_record.notice_name
     *
     * @mbg.generated
     */
    public String getNoticeName() {
        return noticeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_notice_record.notice_name
     *
     * @param noticeName the value for pro_elite_notice_record.notice_name
     *
     * @mbg.generated
     */
    public void setNoticeName(String noticeName) {
        this.noticeName = noticeName == null ? null : noticeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_notice_record.notice_text
     *
     * @return the value of pro_elite_notice_record.notice_text
     *
     * @mbg.generated
     */
    public String getNoticeText() {
        return noticeText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_notice_record.notice_text
     *
     * @param noticeText the value for pro_elite_notice_record.notice_text
     *
     * @mbg.generated
     */
    public void setNoticeText(String noticeText) {
        this.noticeText = noticeText == null ? null : noticeText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_notice_record.is_read
     *
     * @return the value of pro_elite_notice_record.is_read
     *
     * @mbg.generated
     */
    public String getIsRead() {
        return isRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_notice_record.is_read
     *
     * @param isRead the value for pro_elite_notice_record.is_read
     *
     * @mbg.generated
     */
    public void setIsRead(String isRead) {
        this.isRead = isRead == null ? null : isRead.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_notice_record.employee_id
     *
     * @return the value of pro_elite_notice_record.employee_id
     *
     * @mbg.generated
     */
    public String getEmployeeCode() {
        return employeeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_notice_record.employee_id
     *
     * @param employeeCode the value for pro_elite_notice_record.employee_id
     *
     * @mbg.generated
     */
    public void setEmployeeCode(String employeeCode) {
        this.employeeCode = employeeCode == null ? null : employeeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_notice_record.creator_id
     *
     * @return the value of pro_elite_notice_record.creator_id
     *
     * @mbg.generated
     */
    public String getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_notice_record.creator_id
     *
     * @param creatorId the value for pro_elite_notice_record.creator_id
     *
     * @mbg.generated
     */
    public void setCreatorId(String creatorId) {
        this.creatorId = creatorId == null ? null : creatorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_notice_record.create_time
     *
     * @return the value of pro_elite_notice_record.create_time
     *
     * @mbg.generated
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_notice_record.create_time
     *
     * @param createTime the value for pro_elite_notice_record.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_notice_record.ts
     *
     * @return the value of pro_elite_notice_record.ts
     *
     * @mbg.generated
     */
    public Long getTs() {
        return ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_notice_record.ts
     *
     * @param ts the value for pro_elite_notice_record.ts
     *
     * @mbg.generated
     */
    public void setTs(Long ts) {
        this.ts = ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_elite_notice_record.dr
     *
     * @return the value of pro_elite_notice_record.dr
     *
     * @mbg.generated
     */
    public String getDr() {
        return dr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_elite_notice_record.dr
     *
     * @param dr the value for pro_elite_notice_record.dr
     *
     * @mbg.generated
     */
    public void setDr(String dr) {
        this.dr = dr == null ? null : dr.trim();
    }

    public String getEmployeeId() {
        return employeeId;
    }

    public void setEmployeeId(String employeeId) {
        this.employeeId = employeeId;
    }


    public String getNoticeCode() {
        return noticeCode;
    }

    public void setNoticeCode(String noticeCode) {
        this.noticeCode = noticeCode;
    }


}