package models;

public class ProFileRelation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_file_relation.id
     *
     * @mbggenerated Mon Apr 10 16:06:07 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_file_relation.file_id
     *
     * @mbggenerated Mon Apr 10 16:06:07 CST 2017
     */
    private String fileId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_file_relation.bill_id
     *
     * @mbggenerated Mon Apr 10 16:06:07 CST 2017
     */
    private String billId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_file_relation.bill_type
     *
     * @mbggenerated Mon Apr 10 16:06:07 CST 2017
     */
    private String billType;

    private String filePath;

    private String url;

    private String originName;

    private Integer size;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_file_relation.create_time
     *
     * @mbggenerated Mon Apr 10 16:06:07 CST 2017
     */
    private Long createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_file_relation.creator_id
     *
     * @mbggenerated Mon Apr 10 16:06:07 CST 2017
     */
    private String creatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_file_relation.modify_time
     *
     * @mbggenerated Mon Apr 10 16:06:07 CST 2017
     */
    private Long modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_file_relation.modified_id
     *
     * @mbggenerated Mon Apr 10 16:06:07 CST 2017
     */
    private String modifiedId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_file_relation.dr
     *
     * @mbggenerated Mon Apr 10 16:06:07 CST 2017
     */
    private String dr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_file_relation.ts
     *
     * @mbggenerated Mon Apr 10 16:06:07 CST 2017
     */
    private Long ts;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_file_relation.id
     *
     * @return the value of pro_file_relation.id
     *
     * @mbggenerated Mon Apr 10 16:06:07 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_file_relation.id
     *
     * @param id the value for pro_file_relation.id
     *
     * @mbggenerated Mon Apr 10 16:06:07 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_file_relation.file_id
     *
     * @return the value of pro_file_relation.file_id
     *
     * @mbggenerated Mon Apr 10 16:06:07 CST 2017
     */
    public String getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_file_relation.file_id
     *
     * @param fileId the value for pro_file_relation.file_id
     *
     * @mbggenerated Mon Apr 10 16:06:07 CST 2017
     */
    public void setFileId(String fileId) {
        this.fileId = fileId == null ? null : fileId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_file_relation.bill_id
     *
     * @return the value of pro_file_relation.bill_id
     *
     * @mbggenerated Mon Apr 10 16:06:07 CST 2017
     */
    public String getBillId() {
        return billId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_file_relation.bill_id
     *
     * @param billId the value for pro_file_relation.bill_id
     *
     * @mbggenerated Mon Apr 10 16:06:07 CST 2017
     */
    public void setBillId(String billId) {
        this.billId = billId == null ? null : billId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_file_relation.bill_type
     *
     * @return the value of pro_file_relation.bill_type
     *
     * @mbggenerated Mon Apr 10 16:06:07 CST 2017
     */
    public String getBillType() {
        return billType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_file_relation.bill_type
     *
     * @param billType the value for pro_file_relation.bill_type
     *
     * @mbggenerated Mon Apr 10 16:06:07 CST 2017
     */
    public void setBillType(String billType) {
        this.billType = billType == null ? null : billType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_file_relation.create_time
     *
     * @return the value of pro_file_relation.create_time
     *
     * @mbggenerated Mon Apr 10 16:06:07 CST 2017
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_file_relation.create_time
     *
     * @param createTime the value for pro_file_relation.create_time
     *
     * @mbggenerated Mon Apr 10 16:06:07 CST 2017
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_file_relation.creator_id
     *
     * @return the value of pro_file_relation.creator_id
     *
     * @mbggenerated Mon Apr 10 16:06:07 CST 2017
     */
    public String getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_file_relation.creator_id
     *
     * @param creatorId the value for pro_file_relation.creator_id
     *
     * @mbggenerated Mon Apr 10 16:06:07 CST 2017
     */
    public void setCreatorId(String creatorId) {
        this.creatorId = creatorId == null ? null : creatorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_file_relation.modify_time
     *
     * @return the value of pro_file_relation.modify_time
     *
     * @mbggenerated Mon Apr 10 16:06:07 CST 2017
     */
    public Long getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_file_relation.modify_time
     *
     * @param modifyTime the value for pro_file_relation.modify_time
     *
     * @mbggenerated Mon Apr 10 16:06:07 CST 2017
     */
    public void setModifyTime(Long modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_file_relation.modified_id
     *
     * @return the value of pro_file_relation.modified_id
     *
     * @mbggenerated Mon Apr 10 16:06:07 CST 2017
     */
    public String getModifiedId() {
        return modifiedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_file_relation.modified_id
     *
     * @param modifiedId the value for pro_file_relation.modified_id
     *
     * @mbggenerated Mon Apr 10 16:06:07 CST 2017
     */
    public void setModifiedId(String modifiedId) {
        this.modifiedId = modifiedId == null ? null : modifiedId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_file_relation.dr
     *
     * @return the value of pro_file_relation.dr
     *
     * @mbggenerated Mon Apr 10 16:06:07 CST 2017
     */
    public String getDr() {
        return dr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_file_relation.dr
     *
     * @param dr the value for pro_file_relation.dr
     *
     * @mbggenerated Mon Apr 10 16:06:07 CST 2017
     */
    public void setDr(String dr) {
        this.dr = dr == null ? null : dr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_file_relation.ts
     *
     * @return the value of pro_file_relation.ts
     *
     * @mbggenerated Mon Apr 10 16:06:07 CST 2017
     */
    public Long getTs() {
        return ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_file_relation.ts
     *
     * @param ts the value for pro_file_relation.ts
     *
     * @mbggenerated Mon Apr 10 16:06:07 CST 2017
     */
    public void setTs(Long ts) {
        this.ts = ts;
    }

    public String getFilePath() {
        return filePath;
    }

    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getOriginName() {
        return originName;
    }

    public void setOriginName(String originName) {
        this.originName = originName;
    }

    public Integer getSize() {
        return size;
    }

    public void setSize(Integer size) {
        this.size = size;
    }
}