package models;

public class ProShopLobby {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_shop_lobby.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_shop_lobby.employee_id
     *
     * @mbg.generated
     */
    private String employeeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_shop_lobby.employee_code
     *
     * @mbg.generated
     */
    private String employeeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_shop_lobby.enroll_time
     *
     * @mbg.generated
     */
    private String enrollTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_shop_lobby.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_shop_lobby.creator_id
     *
     * @mbg.generated
     */
    private String creatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_shop_lobby.create_time
     *
     * @mbg.generated
     */
    private Long createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_shop_lobby.modifier_id
     *
     * @mbg.generated
     */
    private String modifierId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_shop_lobby.modify_time
     *
     * @mbg.generated
     */
    private Long modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_shop_lobby.ts
     *
     * @mbg.generated
     */
    private Long ts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_shop_lobby.dr
     *
     * @mbg.generated
     */
    private String dr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_shop_lobby.id
     *
     * @return the value of pro_shop_lobby.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_shop_lobby.id
     *
     * @param id the value for pro_shop_lobby.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_shop_lobby.employee_id
     *
     * @return the value of pro_shop_lobby.employee_id
     *
     * @mbg.generated
     */
    public String getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_shop_lobby.employee_id
     *
     * @param employeeId the value for pro_shop_lobby.employee_id
     *
     * @mbg.generated
     */
    public void setEmployeeId(String employeeId) {
        this.employeeId = employeeId == null ? null : employeeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_shop_lobby.employee_code
     *
     * @return the value of pro_shop_lobby.employee_code
     *
     * @mbg.generated
     */
    public String getEmployeeCode() {
        return employeeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_shop_lobby.employee_code
     *
     * @param employeeCode the value for pro_shop_lobby.employee_code
     *
     * @mbg.generated
     */
    public void setEmployeeCode(String employeeCode) {
        this.employeeCode = employeeCode == null ? null : employeeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_shop_lobby.enroll_time
     *
     * @return the value of pro_shop_lobby.enroll_time
     *
     * @mbg.generated
     */
    public String getEnrollTime() {
        return enrollTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_shop_lobby.enroll_time
     *
     * @param enrollTime the value for pro_shop_lobby.enroll_time
     *
     * @mbg.generated
     */
    public void setEnrollTime(String enrollTime) {
        this.enrollTime = enrollTime == null ? null : enrollTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_shop_lobby.status
     *
     * @return the value of pro_shop_lobby.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_shop_lobby.status
     *
     * @param status the value for pro_shop_lobby.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_shop_lobby.creator_id
     *
     * @return the value of pro_shop_lobby.creator_id
     *
     * @mbg.generated
     */
    public String getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_shop_lobby.creator_id
     *
     * @param creatorId the value for pro_shop_lobby.creator_id
     *
     * @mbg.generated
     */
    public void setCreatorId(String creatorId) {
        this.creatorId = creatorId == null ? null : creatorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_shop_lobby.create_time
     *
     * @return the value of pro_shop_lobby.create_time
     *
     * @mbg.generated
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_shop_lobby.create_time
     *
     * @param createTime the value for pro_shop_lobby.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_shop_lobby.modifier_id
     *
     * @return the value of pro_shop_lobby.modifier_id
     *
     * @mbg.generated
     */
    public String getModifierId() {
        return modifierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_shop_lobby.modifier_id
     *
     * @param modifierId the value for pro_shop_lobby.modifier_id
     *
     * @mbg.generated
     */
    public void setModifierId(String modifierId) {
        this.modifierId = modifierId == null ? null : modifierId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_shop_lobby.modify_time
     *
     * @return the value of pro_shop_lobby.modify_time
     *
     * @mbg.generated
     */
    public Long getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_shop_lobby.modify_time
     *
     * @param modifyTime the value for pro_shop_lobby.modify_time
     *
     * @mbg.generated
     */
    public void setModifyTime(Long modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_shop_lobby.ts
     *
     * @return the value of pro_shop_lobby.ts
     *
     * @mbg.generated
     */
    public Long getTs() {
        return ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_shop_lobby.ts
     *
     * @param ts the value for pro_shop_lobby.ts
     *
     * @mbg.generated
     */
    public void setTs(Long ts) {
        this.ts = ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_shop_lobby.dr
     *
     * @return the value of pro_shop_lobby.dr
     *
     * @mbg.generated
     */
    public String getDr() {
        return dr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_shop_lobby.dr
     *
     * @param dr the value for pro_shop_lobby.dr
     *
     * @mbg.generated
     */
    public void setDr(String dr) {
        this.dr = dr == null ? null : dr.trim();
    }
}