package models;

public class ProShopElite {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_shop_elite.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_shop_elite.shop_id
     *
     * @mbg.generated
     */
    private String shopId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_shop_elite.employee_code
     *
     * @mbg.generated
     */
    private String employeeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_shop_elite.employee_id
     *
     * @mbg.generated
     */
    private String employeeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_shop_elite.test_id
     *
     * @mbg.generated
     */
    private String testId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_shop_elite.become_time
     *
     * @mbg.generated
     */
    private Long becomeTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_shop_elite.is_test
     *
     * @mbg.generated
     */
    private String isTest;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_shop_elite.class_status
     *
     * @mbg.generated
     */
    private String classStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_shop_elite.elite_status
     *
     * @mbg.generated
     */
    private String eliteStatus;



    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_shop_elite.elite_pool_referee_id
     *
     * @mbg.generated
     */
    private String elitePoolRefereeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_shop_elite.elite_pool_time
     *
     * @mbg.generated
     */
    private Long elitePoolTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_shop_elite.lobby_referee_id
     *
     * @mbg.generated
     */
    private String lobbyRefereeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_shop_elite.lobby_time
     *
     * @mbg.generated
     */
    private Long lobbyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_shop_elite.manager_referee_id
     *
     * @mbg.generated
     */
    private String managerRefereeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_shop_elite.manager_time
     *
     * @mbg.generated
     */
    private Long managerTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_shop_elite.ts
     *
     * @mbg.generated
     */
    private Long ts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_shop_elite.dr
     *
     * @mbg.generated
     */
    private String dr;


    private  String testRecordId;

    private  String isLobby;

    private String isManager;

    public String getIsLobby() {
        return isLobby;
    }

    public void setIsLobby(String isLobby) {
        this.isLobby = isLobby;
    }

    public String getIsManager() {
        return isManager;
    }

    public void setIsManager(String isManager) {
        this.isManager = isManager;
    }

    public String getTestRecordId() {
        return testRecordId;
    }

    public void setTestRecordId(String testRecordId) {
        this.testRecordId = testRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_shop_elite.id
     *
     * @return the value of pro_shop_elite.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_shop_elite.id
     *
     * @param id the value for pro_shop_elite.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_shop_elite.shop_id
     *
     * @return the value of pro_shop_elite.shop_id
     *
     * @mbg.generated
     */
    public String getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_shop_elite.shop_id
     *
     * @param shopId the value for pro_shop_elite.shop_id
     *
     * @mbg.generated
     */
    public void setShopId(String shopId) {
        this.shopId = shopId == null ? null : shopId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_shop_elite.employee_code
     *
     * @return the value of pro_shop_elite.employee_code
     *
     * @mbg.generated
     */
    public String getEmployeeCode() {
        return employeeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_shop_elite.employee_code
     *
     * @param employeeCode the value for pro_shop_elite.employee_code
     *
     * @mbg.generated
     */
    public void setEmployeeCode(String employeeCode) {
        this.employeeCode = employeeCode == null ? null : employeeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_shop_elite.employee_id
     *
     * @return the value of pro_shop_elite.employee_id
     *
     * @mbg.generated
     */
    public String getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_shop_elite.employee_id
     *
     * @param employeeId the value for pro_shop_elite.employee_id
     *
     * @mbg.generated
     */
    public void setEmployeeId(String employeeId) {
        this.employeeId = employeeId == null ? null : employeeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_shop_elite.test_id
     *
     * @return the value of pro_shop_elite.test_id
     *
     * @mbg.generated
     */
    public String getTestId() {
        return testId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_shop_elite.test_id
     *
     * @param testId the value for pro_shop_elite.test_id
     *
     * @mbg.generated
     */
    public void setTestId(String testId) {
        this.testId = testId == null ? null : testId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_shop_elite.become_time
     *
     * @return the value of pro_shop_elite.become_time
     *
     * @mbg.generated
     */
    public Long getBecomeTime() {
        return becomeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_shop_elite.become_time
     *
     * @param becomeTime the value for pro_shop_elite.become_time
     *
     * @mbg.generated
     */
    public void setBecomeTime(Long becomeTime) {
        this.becomeTime = becomeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_shop_elite.is_test
     *
     * @return the value of pro_shop_elite.is_test
     *
     * @mbg.generated
     */
    public String getIsTest() {
        return isTest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_shop_elite.is_test
     *
     * @param isTest the value for pro_shop_elite.is_test
     *
     * @mbg.generated
     */
    public void setIsTest(String isTest) {
        this.isTest = isTest == null ? null : isTest.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_shop_elite.class_status
     *
     * @return the value of pro_shop_elite.class_status
     *
     * @mbg.generated
     */
    public String getClassStatus() {
        return classStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_shop_elite.class_status
     *
     * @param classStatus the value for pro_shop_elite.class_status
     *
     * @mbg.generated
     */
    public void setClassStatus(String classStatus) {
        this.classStatus = classStatus == null ? null : classStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_shop_elite.elite_status
     *
     * @return the value of pro_shop_elite.elite_status
     *
     * @mbg.generated
     */
    public String getEliteStatus() {
        return eliteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_shop_elite.elite_status
     *
     * @param eliteStatus the value for pro_shop_elite.elite_status
     *
     * @mbg.generated
     */
    public void setEliteStatus(String eliteStatus) {
        this.eliteStatus = eliteStatus == null ? null : eliteStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_shop_elite.test_time
     *
     * @return the value of pro_shop_elite.test_time
     *
     * @mbg.generated
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_shop_elite.elite_pool_referee_id
     *
     * @return the value of pro_shop_elite.elite_pool_referee_id
     *
     * @mbg.generated
     */
    public String getElitePoolRefereeId() {
        return elitePoolRefereeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_shop_elite.elite_pool_referee_id
     *
     * @param elitePoolRefereeId the value for pro_shop_elite.elite_pool_referee_id
     *
     * @mbg.generated
     */
    public void setElitePoolRefereeId(String elitePoolRefereeId) {
        this.elitePoolRefereeId = elitePoolRefereeId == null ? null : elitePoolRefereeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_shop_elite.elite_pool_time
     *
     * @return the value of pro_shop_elite.elite_pool_time
     *
     * @mbg.generated
     */
    public Long getElitePoolTime() {
        return elitePoolTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_shop_elite.elite_pool_time
     *
     * @param elitePoolTime the value for pro_shop_elite.elite_pool_time
     *
     * @mbg.generated
     */
    public void setElitePoolTime(Long elitePoolTime) {
        this.elitePoolTime = elitePoolTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_shop_elite.lobby_referee_id
     *
     * @return the value of pro_shop_elite.lobby_referee_id
     *
     * @mbg.generated
     */
    public String getLobbyRefereeId() {
        return lobbyRefereeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_shop_elite.lobby_referee_id
     *
     * @param lobbyRefereeId the value for pro_shop_elite.lobby_referee_id
     *
     * @mbg.generated
     */
    public void setLobbyRefereeId(String lobbyRefereeId) {
        this.lobbyRefereeId = lobbyRefereeId == null ? null : lobbyRefereeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_shop_elite.lobby_time
     *
     * @return the value of pro_shop_elite.lobby_time
     *
     * @mbg.generated
     */
    public Long getLobbyTime() {
        return lobbyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_shop_elite.lobby_time
     *
     * @param lobbyTime the value for pro_shop_elite.lobby_time
     *
     * @mbg.generated
     */
    public void setLobbyTime(Long lobbyTime) {
        this.lobbyTime = lobbyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_shop_elite.manager_referee_id
     *
     * @return the value of pro_shop_elite.manager_referee_id
     *
     * @mbg.generated
     */
    public String getManagerRefereeId() {
        return managerRefereeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_shop_elite.manager_referee_id
     *
     * @param managerRefereeId the value for pro_shop_elite.manager_referee_id
     *
     * @mbg.generated
     */
    public void setManagerRefereeId(String managerRefereeId) {
        this.managerRefereeId = managerRefereeId == null ? null : managerRefereeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_shop_elite.manager_time
     *
     * @return the value of pro_shop_elite.manager_time
     *
     * @mbg.generated
     */
    public Long getManagerTime() {
        return managerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_shop_elite.manager_time
     *
     * @param managerTime the value for pro_shop_elite.manager_time
     *
     * @mbg.generated
     */
    public void setManagerTime(Long managerTime) {
        this.managerTime = managerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_shop_elite.ts
     *
     * @return the value of pro_shop_elite.ts
     *
     * @mbg.generated
     */
    public Long getTs() {
        return ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_shop_elite.ts
     *
     * @param ts the value for pro_shop_elite.ts
     *
     * @mbg.generated
     */
    public void setTs(Long ts) {
        this.ts = ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_shop_elite.dr
     *
     * @return the value of pro_shop_elite.dr
     *
     * @mbg.generated
     */
    public String getDr() {
        return dr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_shop_elite.dr
     *
     * @param dr the value for pro_shop_elite.dr
     *
     * @mbg.generated
     */
    public void setDr(String dr) {
        this.dr = dr == null ? null : dr.trim();
    }
}