package models;

public class ProShopEliteEmployee {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_shop_elite_employee.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_shop_elite_employee.employee_id
     *
     * @mbg.generated
     */
    private String employeeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_shop_elite_employee.emoployee_code
     *
     * @mbg.generated
     */
    private String emoployeeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_shop_elite_employee.is_manager
     *
     * @mbg.generated
     */
    private String isManager;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_shop_elite_employee.enable
     *
     * @mbg.generated
     */
    private String enable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_shop_elite_employee.elite_level
     *
     * @mbg.generated
     */
    private String eliteLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_shop_elite_employee.shop_id
     *
     * @mbg.generated
     */
    private String shopId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_shop_elite_employee.creator_id
     *
     * @mbg.generated
     */
    private String creatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_shop_elite_employee.create_time
     *
     * @mbg.generated
     */
    private Long createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_shop_elite_employee.modifier_id
     *
     * @mbg.generated
     */
    private String modifierId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_shop_elite_employee.modify_time
     *
     * @mbg.generated
     */
    private Long modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_shop_elite_employee.ts
     *
     * @mbg.generated
     */
    private Long ts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_shop_elite_employee.dr
     *
     * @mbg.generated
     */
    private String dr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_shop_elite_employee.id
     *
     * @return the value of pro_shop_elite_employee.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_shop_elite_employee.id
     *
     * @param id the value for pro_shop_elite_employee.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_shop_elite_employee.employee_id
     *
     * @return the value of pro_shop_elite_employee.employee_id
     *
     * @mbg.generated
     */
    public String getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_shop_elite_employee.employee_id
     *
     * @param employeeId the value for pro_shop_elite_employee.employee_id
     *
     * @mbg.generated
     */
    public void setEmployeeId(String employeeId) {
        this.employeeId = employeeId == null ? null : employeeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_shop_elite_employee.emoployee_code
     *
     * @return the value of pro_shop_elite_employee.emoployee_code
     *
     * @mbg.generated
     */
    public String getEmoployeeCode() {
        return emoployeeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_shop_elite_employee.emoployee_code
     *
     * @param emoployeeCode the value for pro_shop_elite_employee.emoployee_code
     *
     * @mbg.generated
     */
    public void setEmoployeeCode(String emoployeeCode) {
        this.emoployeeCode = emoployeeCode == null ? null : emoployeeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_shop_elite_employee.is_manager
     *
     * @return the value of pro_shop_elite_employee.is_manager
     *
     * @mbg.generated
     */
    public String getIsManager() {
        return isManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_shop_elite_employee.is_manager
     *
     * @param isManager the value for pro_shop_elite_employee.is_manager
     *
     * @mbg.generated
     */
    public void setIsManager(String isManager) {
        this.isManager = isManager == null ? null : isManager.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_shop_elite_employee.enable
     *
     * @return the value of pro_shop_elite_employee.enable
     *
     * @mbg.generated
     */
    public String getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_shop_elite_employee.enable
     *
     * @param enable the value for pro_shop_elite_employee.enable
     *
     * @mbg.generated
     */
    public void setEnable(String enable) {
        this.enable = enable == null ? null : enable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_shop_elite_employee.elite_level
     *
     * @return the value of pro_shop_elite_employee.elite_level
     *
     * @mbg.generated
     */
    public String getEliteLevel() {
        return eliteLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_shop_elite_employee.elite_level
     *
     * @param eliteLevel the value for pro_shop_elite_employee.elite_level
     *
     * @mbg.generated
     */
    public void setEliteLevel(String eliteLevel) {
        this.eliteLevel = eliteLevel == null ? null : eliteLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_shop_elite_employee.shop_id
     *
     * @return the value of pro_shop_elite_employee.shop_id
     *
     * @mbg.generated
     */
    public String getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_shop_elite_employee.shop_id
     *
     * @param shopId the value for pro_shop_elite_employee.shop_id
     *
     * @mbg.generated
     */
    public void setShopId(String shopId) {
        this.shopId = shopId == null ? null : shopId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_shop_elite_employee.creator_id
     *
     * @return the value of pro_shop_elite_employee.creator_id
     *
     * @mbg.generated
     */
    public String getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_shop_elite_employee.creator_id
     *
     * @param creatorId the value for pro_shop_elite_employee.creator_id
     *
     * @mbg.generated
     */
    public void setCreatorId(String creatorId) {
        this.creatorId = creatorId == null ? null : creatorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_shop_elite_employee.create_time
     *
     * @return the value of pro_shop_elite_employee.create_time
     *
     * @mbg.generated
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_shop_elite_employee.create_time
     *
     * @param createTime the value for pro_shop_elite_employee.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_shop_elite_employee.modifier_id
     *
     * @return the value of pro_shop_elite_employee.modifier_id
     *
     * @mbg.generated
     */
    public String getModifierId() {
        return modifierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_shop_elite_employee.modifier_id
     *
     * @param modifierId the value for pro_shop_elite_employee.modifier_id
     *
     * @mbg.generated
     */
    public void setModifierId(String modifierId) {
        this.modifierId = modifierId == null ? null : modifierId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_shop_elite_employee.modify_time
     *
     * @return the value of pro_shop_elite_employee.modify_time
     *
     * @mbg.generated
     */
    public Long getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_shop_elite_employee.modify_time
     *
     * @param modifyTime the value for pro_shop_elite_employee.modify_time
     *
     * @mbg.generated
     */
    public void setModifyTime(Long modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_shop_elite_employee.ts
     *
     * @return the value of pro_shop_elite_employee.ts
     *
     * @mbg.generated
     */
    public Long getTs() {
        return ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_shop_elite_employee.ts
     *
     * @param ts the value for pro_shop_elite_employee.ts
     *
     * @mbg.generated
     */
    public void setTs(Long ts) {
        this.ts = ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_shop_elite_employee.dr
     *
     * @return the value of pro_shop_elite_employee.dr
     *
     * @mbg.generated
     */
    public String getDr() {
        return dr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_shop_elite_employee.dr
     *
     * @param dr the value for pro_shop_elite_employee.dr
     *
     * @mbg.generated
     */
    public void setDr(String dr) {
        this.dr = dr == null ? null : dr.trim();
    }
}