package models;

public class ProUploadFile {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_upload_file.id
     *
     * @mbggenerated Mon Apr 10 10:29:22 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_upload_file.origin_name
     *
     * @mbggenerated Mon Apr 10 10:29:22 CST 2017
     */
    private String originName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_upload_file.file_name
     *
     * @mbggenerated Mon Apr 10 10:29:22 CST 2017
     */
    private String fileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_upload_file.size
     *
     * @mbggenerated Mon Apr 10 10:29:22 CST 2017
     */
    private Integer size;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_upload_file.file_path
     *
     * @mbggenerated Mon Apr 10 10:29:22 CST 2017
     */
    private String filePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_upload_file.url
     *
     * @mbggenerated Mon Apr 10 10:29:22 CST 2017
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_upload_file.create_time
     *
     * @mbggenerated Mon Apr 10 10:29:22 CST 2017
     */
    private Long createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_upload_file.creator_id
     *
     * @mbggenerated Mon Apr 10 10:29:22 CST 2017
     */
    private String creatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_upload_file.modify_time
     *
     * @mbggenerated Mon Apr 10 10:29:22 CST 2017
     */
    private Long modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_upload_file.modifier_id
     *
     * @mbggenerated Mon Apr 10 10:29:22 CST 2017
     */
    private String modifierId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_upload_file.dr
     *
     * @mbggenerated Mon Apr 10 10:29:22 CST 2017
     */
    private String dr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pro_upload_file.ts
     *
     * @mbggenerated Mon Apr 10 10:29:22 CST 2017
     */
    private Long ts;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_upload_file.id
     *
     * @return the value of pro_upload_file.id
     *
     * @mbggenerated Mon Apr 10 10:29:22 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_upload_file.id
     *
     * @param id the value for pro_upload_file.id
     *
     * @mbggenerated Mon Apr 10 10:29:22 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_upload_file.origin_name
     *
     * @return the value of pro_upload_file.origin_name
     *
     * @mbggenerated Mon Apr 10 10:29:22 CST 2017
     */
    public String getOriginName() {
        return originName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_upload_file.origin_name
     *
     * @param originName the value for pro_upload_file.origin_name
     *
     * @mbggenerated Mon Apr 10 10:29:22 CST 2017
     */
    public void setOriginName(String originName) {
        this.originName = originName == null ? null : originName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_upload_file.file_name
     *
     * @return the value of pro_upload_file.file_name
     *
     * @mbggenerated Mon Apr 10 10:29:22 CST 2017
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_upload_file.file_name
     *
     * @param fileName the value for pro_upload_file.file_name
     *
     * @mbggenerated Mon Apr 10 10:29:22 CST 2017
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_upload_file.size
     *
     * @return the value of pro_upload_file.size
     *
     * @mbggenerated Mon Apr 10 10:29:22 CST 2017
     */
    public Integer getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_upload_file.size
     *
     * @param size the value for pro_upload_file.size
     *
     * @mbggenerated Mon Apr 10 10:29:22 CST 2017
     */
    public void setSize(Integer size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_upload_file.file_path
     *
     * @return the value of pro_upload_file.file_path
     *
     * @mbggenerated Mon Apr 10 10:29:22 CST 2017
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_upload_file.file_path
     *
     * @param filePath the value for pro_upload_file.file_path
     *
     * @mbggenerated Mon Apr 10 10:29:22 CST 2017
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath == null ? null : filePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_upload_file.url
     *
     * @return the value of pro_upload_file.url
     *
     * @mbggenerated Mon Apr 10 10:29:22 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_upload_file.url
     *
     * @param url the value for pro_upload_file.url
     *
     * @mbggenerated Mon Apr 10 10:29:22 CST 2017
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_upload_file.create_time
     *
     * @return the value of pro_upload_file.create_time
     *
     * @mbggenerated Mon Apr 10 10:29:22 CST 2017
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_upload_file.create_time
     *
     * @param createTime the value for pro_upload_file.create_time
     *
     * @mbggenerated Mon Apr 10 10:29:22 CST 2017
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_upload_file.creator_id
     *
     * @return the value of pro_upload_file.creator_id
     *
     * @mbggenerated Mon Apr 10 10:29:22 CST 2017
     */
    public String getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_upload_file.creator_id
     *
     * @param creatorId the value for pro_upload_file.creator_id
     *
     * @mbggenerated Mon Apr 10 10:29:22 CST 2017
     */
    public void setCreatorId(String creatorId) {
        this.creatorId = creatorId == null ? null : creatorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_upload_file.modify_time
     *
     * @return the value of pro_upload_file.modify_time
     *
     * @mbggenerated Mon Apr 10 10:29:22 CST 2017
     */
    public Long getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_upload_file.modify_time
     *
     * @param modifyTime the value for pro_upload_file.modify_time
     *
     * @mbggenerated Mon Apr 10 10:29:22 CST 2017
     */
    public void setModifyTime(Long modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_upload_file.modifier_id
     *
     * @return the value of pro_upload_file.modifier_id
     *
     * @mbggenerated Mon Apr 10 10:29:22 CST 2017
     */
    public String getModifierId() {
        return modifierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_upload_file.modifier_id
     *
     * @param modifierId the value for pro_upload_file.modifier_id
     *
     * @mbggenerated Mon Apr 10 10:29:22 CST 2017
     */
    public void setModifierId(String modifierId) {
        this.modifierId = modifierId == null ? null : modifierId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_upload_file.dr
     *
     * @return the value of pro_upload_file.dr
     *
     * @mbggenerated Mon Apr 10 10:29:22 CST 2017
     */
    public String getDr() {
        return dr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_upload_file.dr
     *
     * @param dr the value for pro_upload_file.dr
     *
     * @mbggenerated Mon Apr 10 10:29:22 CST 2017
     */
    public void setDr(String dr) {
        this.dr = dr == null ? null : dr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pro_upload_file.ts
     *
     * @return the value of pro_upload_file.ts
     *
     * @mbggenerated Mon Apr 10 10:29:22 CST 2017
     */
    public Long getTs() {
        return ts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pro_upload_file.ts
     *
     * @param ts the value for pro_upload_file.ts
     *
     * @mbggenerated Mon Apr 10 10:29:22 CST 2017
     */
    public void setTs(Long ts) {
        this.ts = ts;
    }
}